/**
 * This file is autogenerated from gql:compile script using editCodespace.graphql .
 * Any changes made to this file will be overwritten in build.
 * It won't be committed into git.
 **/

import {OperationTypeNode} from 'graphql'

export interface EditCodespaceInput {
  projectId?: string | null;
  codespaceId?: string | null;
  codespaceName?: string | null;
}

export interface SelectionOnEditCodespace {
  status: string | null;
}

export interface EditCodespace {
  editCodespace: SelectionOnEditCodespace | null;
}

export interface GraphQLWrapper {
  query: string
  name: string
  operation: OperationTypeNode
 }
export declare const GQL: GraphQLWrapper