/**
 * This file is autogenerated from gql:compile script using getCodespaces.graphql .
 * Any changes made to this file will be overwritten in build.
 * It won't be committed into git.
 **/

import {OperationTypeNode} from 'graphql'

export interface GetCodespacesInput {
  projectId?: string | null;
}

export interface SelectionOnData {
  codespace_id: string | null;
  codespace_name: string | null;
  created_by: string | null;
}

export interface SelectionOnGetCodespaces {
  status: string | null;
  data: Array<SelectionOnData | null> | null;
}

export interface GetCodespaces {
  getCodespaces: SelectionOnGetCodespaces | null;
}

export interface GraphQLWrapper {
  query: string
  name: string
  operation: OperationTypeNode
 }
export declare const GQL: GraphQLWrapper