/**
 * This file is autogenerated from gql:compile script using index.graphql .
 * Any changes made to this file will be overwritten in build.
 * It won't be committed into git.
 **/

import {OperationTypeNode} from 'graphql'
import {ApiStatus} from '../../../../../gql-enums/api-status.enum'
import {LibraryStatus} from '../../../../../gql-enums/library-status.enum'
export interface GetComputeLibraryStatusInput {
  cluster_id?: string | null;
  library_id?: number | null;
}

export interface SelectionOnData {
  cluster_id: string | null;
  library_id: number | null;
  status: LibraryStatus | null;
}

export interface SelectionOnGetComputeLibraryStatus {
  status: ApiStatus | null;
  message: string | null;
  data: SelectionOnData | null;
}

export interface GetComputeLibraryStatus {
  getComputeLibraryStatus: SelectionOnGetComputeLibraryStatus | null;
}


export interface GraphQLWrapper {
  query: string
  name: string
  operation: OperationTypeNode
 }
export declare const GQL: GraphQLWrapper