/**
 * This file is autogenerated from gql:compile script using index.graphql .
 * Any changes made to this file will be overwritten in build.
 * It won't be committed into git.
 **/

import {OperationTypeNode} from 'graphql'

export interface GetLogLineDetailsInput {
  processedEventId?: number | null;
}

export interface SelectionOnData {
  processed_event_id: number | null;
  event_data: any | null;
  timestamp: string | null;
}

export interface SelectionOnGetLogLineDetails {
  data: SelectionOnData | null;
}

export interface GetLogLineDetails {
  getLogLineDetails: SelectionOnGetLogLineDetails | null;
}

export interface GraphQLWrapper {
  query: string
  name: string
  operation: OperationTypeNode
 }
export declare const GQL: GraphQLWrapper