/**
 * This file is autogenerated from gql:compile script using predictClusterCost.graphql .
 * Any changes made to this file will be overwritten in build.
 * It won't be committed into git.
 **/

import {OperationTypeNode} from 'graphql'

export interface PredictClusterCostInput {
  input?: {
    clusterName?: string | null;
    tags?: Array<string | null> | null;
    runtime?: string | null;
    inactiveTime?: number | null;
    user?: string | null;
    headNodeConfig?: any | null;
    workerNodeConfigs?: Array<any | null> | null;
  } | null;
}

export interface SelectionOnData {
  min_cost: string | null;
  max_cost: string | null;
}

export interface SelectionOnPredictClusterCost {
  data: SelectionOnData | null;
}

export interface PredictClusterCost {
  predictClusterCost: SelectionOnPredictClusterCost | null;
}

export interface GraphQLWrapper {
  query: string
  name: string
  operation: OperationTypeNode
 }
export declare const GQL: GraphQLWrapper