/**
 * This file is autogenerated from gql:compile script using index.graphql .
 * Any changes made to this file will be overwritten in build.
 * It won't be committed into git.
 **/

import {OperationTypeNode} from 'graphql'

export interface DeleteWorkflowInput {
  workflowId?: string | null;
}

export interface SelectionOnData {
  workflow_id: string | null;
  is_deleted: boolean | null;
}

export interface SelectionOnDeleteWorkflow {
  data: SelectionOnData | null;
}

export interface DeleteWorkflow {
  deleteWorkflow: SelectionOnDeleteWorkflow | null;
}

export interface GraphQLWrapper {
  query: string
  name: string
  operation: OperationTypeNode
 }
export declare const GQL: GraphQLWrapper