/**
 * This file is autogenerated from gql:compile script using fetchScheduleJobRuns.graphql .
 * Any changes made to this file will be overwritten in build.
 * It won't be committed into git.
 **/

import {OperationTypeNode} from 'graphql'

export interface FetchScheduleJobRunsInput {
  featureJobId?: string | null;
  version?: number | null;
  limit?: number | null;
  offset?: number | null;
}

export interface SelectionOnSchedulerJobRunDetails {
  backfillId: number | null;
  queryRunType: string | null;
  jobStatusRun: string | null;
  yarnUrl: string | null;
  resourceTier: string | null;
  comment: string | null;
  createdAt: string | null;
  updatedAt: string | null;
}

export interface SelectionOnResponse {
  schedulerJobRunDetails: Array<SelectionOnSchedulerJobRunDetails | null> | null;
}

export interface SelectionOnFetchScheduleJobRuns {
  message: string | null;
  comments: Array<string | null> | null;
  response: SelectionOnResponse | null;
}

export interface FetchScheduleJobRuns {
  fetchScheduleJobRuns: SelectionOnFetchScheduleJobRuns | null;
}

export interface GraphQLWrapper {
  query: string
  name: string
  operation: OperationTypeNode
 }
export declare const GQL: GraphQLWrapper