/**
 * This file is autogenerated from gql:compile script using index.graphql .
 * Any changes made to this file will be overwritten in build.
 * It won't be committed into git.
 **/

import {OperationTypeNode} from 'graphql'
import {ApiStatus} from '../../../../../gql-enums/api-status.enum'
import {LibraryFileType} from '../../../../../gql-enums/library-file-type.enum'
import {LibrarySource} from '../../../../../gql-enums/library-source.enum'
import {LibraryStatus} from '../../../../../gql-enums/library-status.enum'
export interface GetComputeLibraryDetailsInput {
  cluster_id?: string | null;
  library_id?: number | null;
}

export interface SelectionOnError {
  error_code: string | null;
  error_message: string | null;
}

export interface SelectionOnData {
  cluster_id: string | null;
  id: number | null;
  name: string | null;
  version: string | null;
  type: LibraryFileType | null;
  source: LibrarySource | null;
  path: string | null;
  status: LibraryStatus | null;
  content: string | null;
  error: SelectionOnError | null;
}

export interface SelectionOnGetComputeLibraryDetails {
  status: ApiStatus | null;
  message: string | null;
  data: SelectionOnData | null;
}

export interface GetComputeLibraryDetails {
  getComputeLibraryDetails: SelectionOnGetComputeLibraryDetails | null;
}


export interface GraphQLWrapper {
  query: string
  name: string
  operation: OperationTypeNode
 }
export declare const GQL: GraphQLWrapper