/**
 * This file is autogenerated from gql:compile script using index.graphql .
 * Any changes made to this file will be overwritten in build.
 * It won't be committed into git.
 **/

import {OperationTypeNode} from 'graphql'
import {ApiStatus} from '../../../../../gql-enums/api-status.enum'
import {LibraryStatus} from '../../../../../gql-enums/library-status.enum'
export interface RetryInstallLibraryInput {
  input?: {
    cluster_id?: string | null;
    library_id?: number | null;
  } | null;
}

export interface SelectionOnPackages {
  status: LibraryStatus | null;
  version: string | null;
  name: string | null;
  id: string | null;
}

export interface SelectionOnData {
  packages: Array<SelectionOnPackages | null> | null;
  cluster_id: string | null;
}

export interface SelectionOnRetryInstallLibrary {
  status: ApiStatus | null;
  message: string | null;
  data: SelectionOnData | null;
}

export interface RetryInstallLibrary {
  retryInstallLibrary: SelectionOnRetryInstallLibrary | null;
}


export interface GraphQLWrapper {
  query: string
  name: string
  operation: OperationTypeNode
 }
export declare const GQL: GraphQLWrapper