/**
 * This file is autogenerated from gql:compile script using checkUniqueCodespace.graphql .
 * Any changes made to this file will be overwritten in build.
 * It won't be committed into git.
 **/

import {OperationTypeNode} from 'graphql'

export interface CheckUniqueCodespaceInput {
  projectId?: string | null;
  codespaceName?: string | null;
}

export interface SelectionOnData {
  is_unique: boolean | null;
}

export interface SelectionOnCheckUniqueCodespace {
  status: string | null;
  data: SelectionOnData | null;
}

export interface CheckUniqueCodespace {
  checkUniqueCodespace: SelectionOnCheckUniqueCodespace | null;
}

export interface GraphQLWrapper {
  query: string
  name: string
  operation: OperationTypeNode
 }
export declare const GQL: GraphQLWrapper