/**
 * This file is autogenerated from gql:compile script using index.graphql .
 * Any changes made to this file will be overwritten in build.
 * It won't be committed into git.
 **/

import {OperationTypeNode} from 'graphql'

export interface CodespaceFoldersInput {
  codespaceId?: string | null;
  folderPath?: string | null;
}

export interface SelectionOnFiles {
  name: string | null;
}

export interface SelectionOnSubFolders {
  name: string | null;
}

export interface SelectionOnData {
  files: Array<SelectionOnFiles | null> | null;
  sub_folders: Array<SelectionOnSubFolders | null> | null;
}

export interface SelectionOnCodespaceFolders {
  status: string | null;
  data: SelectionOnData | null;
}

export interface CodespaceFolders {
  codespaceFolders: SelectionOnCodespaceFolders | null;
}

export interface GraphQLWrapper {
  query: string
  name: string
  operation: OperationTypeNode
 }
export declare const GQL: GraphQLWrapper