/**
 * This file is autogenerated from gql:compile script using index.graphql .
 * Any changes made to this file will be overwritten in build.
 * It won't be committed into git.
 **/

import {OperationTypeNode} from 'graphql'

export interface SelectionOnData {
  event: string;
  default: boolean;
}

export interface SelectionOnGetEventTypes {
  data: Array<SelectionOnData>;
}

export interface GetEventTypes {
  getEventTypes: SelectionOnGetEventTypes | null;
}

export interface GraphQLWrapper {
  query: string
  name: string
  operation: OperationTypeNode
 }
export declare const GQL: GraphQLWrapper