/**
 * This file is autogenerated from gql:compile script using index.graphql .
 * Any changes made to this file will be overwritten in build.
 * It won't be committed into git.
 **/

import {OperationTypeNode} from 'graphql'

export interface GetLogsInput {
  clusterId?: string | null;
  pageSize?: number | null;
  offset?: number | null;
  lastEventId?: number | null;
  filters?: {
    severities?: Array<string | null> | null;
    start_timestamp?: string | null;
    end_timestamp?: string | null;
    components?: Array<number | null> | null;
    event_types?: Array<string | null> | null;
  } | null;
}

export interface SelectionOnData {
  raw_event_id: number | null;
  processed_event_id: number | null;
  timestamp: string | null;
  event_type: string | null;
  message: string | null;
  severity: string | null;
  source_id: number | null;
}

export interface SelectionOnGetLogs {
  status: string | null;
  page_size: number | null;
  offset: number | null;
  data: Array<SelectionOnData | null> | null;
}

export interface GetLogs {
  getLogs: SelectionOnGetLogs | null;
}

export interface GraphQLWrapper {
  query: string
  name: string
  operation: OperationTypeNode
 }
export declare const GQL: GraphQLWrapper