export const CREATE_PROJECT = 'workspace/createProject'
export const CREATE_CODESPACE = 'workspace/createCodespace'
export const PROJECT_DETAILS = 'workspace/projectDetails'
export const LIST_PROJECT = 'workspace/listProject'
export const GET_CODESPACES = 'workspace/getCodespaces'
export const SET_LAST_SELECTED_CODESPACE = 'workspace/setLastSelectedCodespace'
export const SET_GET_ALL_CLUSTERS = 'workspace/getAllClusters'
export const SET_LAUNCH_CODESPACE = 'workspace/launchCodespace'
export const SET_SELECTED_CODESPACE = 'workspace/selectedCodespace'
export const SET_DETACH_CLUSTER = 'workspace/setDetachCluster'
export const SET_SELECTED_PROJECT = 'workspace/setSelectedProject'
export const SET_ATTACH_CLUSTER = 'workspace/setAttachCluster'
export const SET_START_CLUSTER = 'workspace/setStartCluster'
export const SET_STOP_CLUSTER = 'workspace/setStopCluster'
export const SET_IMPORT_PROJECT = 'workspace/importProject'
export const SET_ATTACHED_CLUSTER = 'workspace/setAttachedCluster'
export const SET_LAST_SYNC_TIME = 'workspace/setLastSyncTime'
export const SET_SIDE_BAR_CONFIG = 'workspace/setSideBarConfig'
export const SET_GENERIC_SNACKBAR = 'workspace/setGenericSnackBar'
export const SET_UNIQUE_LINK = 'workspace/setUniqueLink'
export const SET_UNIQUE_PROJECT = 'workspace/setUniqueProject'
export const SET_UNIQUE_CODESPACE = 'workspace/setUniqueCodespace'
export const SET_ENVIRONMENT = 'workspace/setEnvironment'
export const SET_DATA_SOURCES_FOR_ENVIRONMENT =
  'workspace/setDataSourcesForEnvironment'
export const SET_DATA_FOR_ENVIRONMENT_AND_SOURCE =
  'workspace/setDataForEnvironmentAndSource'
export const SET_SAMPLE_DATA_FOR_DATA_SOURCE =
  'workspace/setSampleDataForDataSource'
export const SET_CLUSTER_RESOURCES = 'workspace/setClusterResources'
export const SET_CLUSTER_CANCELLATION_FOR_POLLING =
  'workspace/setClusterCancellationForPolling'
export const SET_DELETE_PROJECT = 'workspace/setDeleteProject'
export const SET_DELETE_CODESPACE = 'workspace/setDeleteCodespace'
export const SET_EDIT_CODESPACE = 'workspace/setEditCodespace'
export const SET_EDIT_PROJECT = 'workspace/setEditProject'
export const SET_COUNT_OF_PROJECTS = 'workspace/setCountOfProjects'
export const SET_DATABASES_FOR_ENVIRONMENT_AND_SOURCE =
  'workspace/setDatabasesForEnvironmentAndSource'
export const SET_INFO_BAR = 'workspace/setInfoBar'
export const SET_WORKSPACE_CLUSTER_STATUS =
  'workspace/setWorkspaceClusterStatus'
