/**
 * This file is autogenerated from gql:compile script using createComputeCluster.graphql .
 * Any changes made to this file will be overwritten in build.
 * It won't be committed into git.
 **/

import {OperationTypeNode} from 'graphql'

export interface CreateComputeClusterInput {
  input?: {
    clusterName?: string | null;
    packages_clone_from?: string | null;
    tags?: Array<string | null> | null;
    runtime?: string | null;
    inactiveTime?: number | null;
    autoTerminationPolicies?: Array<any | null> | null;
    template?: any | null;
    user?: string | null;
    headNodeConfig?: any | null;
    workerNodeConfigs?: Array<any | null> | null;
    advanceConfig?: any | null;
  } | null;
}

export interface SelectionOnData {
  cluster_id: string | null;
}

export interface SelectionOnCreateComputeCluster {
  status: string | null;
  data: SelectionOnData | null;
}

export interface CreateComputeCluster {
  createComputeCluster: SelectionOnCreateComputeCluster | null;
}

export interface GraphQLWrapper {
  query: string
  name: string
  operation: OperationTypeNode
 }
export declare const GQL: GraphQLWrapper