/**
 * This file is autogenerated from gql:compile script using getClusterStatus.graphql .
 * Any changes made to this file will be overwritten in build.
 * It won't be committed into git.
 **/

import {OperationTypeNode} from 'graphql'

export interface GetComputeClusterInput {
  clusterId?: string | null;
}

export interface SelectionOnData {
  clusterId: string | null;
  clusterName: string | null;
  status: string | null;
}

export interface SelectionOnGetComputeCluster {
  status: string | null;
  data: SelectionOnData | null;
}

export interface GetComputeCluster {
  getComputeCluster: SelectionOnGetComputeCluster | null;
}

export interface GraphQLWrapper {
  query: string
  name: string
  operation: OperationTypeNode
 }
export declare const GQL: GraphQLWrapper