/**
 * This file is autogenerated from gql:compile script using index.graphql .
 * Any changes made to this file will be overwritten in build.
 * It won't be committed into git.
 **/

import {OperationTypeNode} from 'graphql'
import {RepositoryType} from '../../../../gql-enums/repository-type.enum'
import {TriggerRules} from '../../../../gql-enums/trigger-rules.enum'
export interface CreateWorkflowInput {
  input?: {
    workflowName?: string | null;
    description?: string | null;
    displayName?: string | null;
    tags?: Array<string | null> | null;
    maxConcurrentRuns?: number | null;
    expected_run_duration?: number | null;
    queue_enabled?: boolean | null;
    notification_preference?: any | null;
    schedule?: string | null;
    retries?: number | null;
    notifyOn?: string | null;
    parameters?: any | null;
    tasks?: Array<any | null> | null;
    createdBy?: string | null;
  } | null;
}

export interface SelectionOnNotificationPreference {
  on_fail: boolean | null;
  on_skip: boolean | null;
  on_success: boolean | null;
  on_start: boolean | null;
}

export interface SelectionOnAttachedCluster {
  cluster_id: string | null;
  runtime: string | null;
  cluster_name: string | null;
  cluster_status: string | null;
  memory: number | null;
  cores: number | null;
  ray_dashboard: string | null;
  logs_dashboard: string | null;
  events_dashboard: string | null;
  estimated_cost: string | null;
  created_at: string | null;
}

export interface SelectionOnMetadata {
  repository: RepositoryType | null;
  exclusions: string | null;
}

export interface SelectionOnBody {
  path: string | null;
  name: string | null;
  version: string | null;
  metadata: SelectionOnMetadata | null;
}

export interface SelectionOnPackages {
  source: string | null;
  body: SelectionOnBody | null;
}

export interface SelectionOnHaConfig {
  enable_ha: boolean | null;
}

export interface SelectionOnNotificationPreference1 {
  on_fail: boolean | null;
}

export interface SelectionOnTasks {
  task_name: string | null;
  source_type: string | null;
  source: string | null;
  file_path: string | null;
  dynamic_artifact: boolean | null;
  cluster_type: string | null;
  attached_cluster: SelectionOnAttachedCluster | null;
  dependent_libraries: string | null;
  packages: Array<SelectionOnPackages | null> | null;
  input_parameters: any | null;
  retries: number | null;
  timeout: number | null;
  depends_on: Array<string | null> | null;
  task_validation_status: string | null;
  run_status: string | null;
  ha_config: SelectionOnHaConfig | null;
  notify_on: string | null;
  notification_preference: SelectionOnNotificationPreference1 | null;
  trigger_rule: TriggerRules | null;
}

export interface SelectionOnData {
  workflow_id: string | null;
  workflow_name: string | null;
  display_name: string | null;
  description: string | null;
  tags: Array<string | null> | null;
  schedule: string | null;
  retries: number | null;
  notify_on: string | null;
  parameters: any | null;
  max_concurrent_runs: number | null;
  queue_enabled: boolean | null;
  expected_run_duration: number | null;
  notification_preference: SelectionOnNotificationPreference | null;
  created_by: string | null;
  last_updated_on: string | null;
  created_at: string | null;
  workflow_status: string | null;
  tasks: Array<SelectionOnTasks | null> | null;
  next_run_time: string | null;
}

export interface SelectionOnCreateWorkflow {
  data: SelectionOnData | null;
}

export interface CreateWorkflow {
  createWorkflow: SelectionOnCreateWorkflow | null;
}


export interface GraphQLWrapper {
  query: string
  name: string
  operation: OperationTypeNode
 }
export declare const GQL: GraphQLWrapper