/**
 * This file is autogenerated from gql:compile script using index.graphql .
 * Any changes made to this file will be overwritten in build.
 * It won't be committed into git.
 **/

import {OperationTypeNode} from 'graphql'
import {ApiStatus} from '../../../../../gql-enums/api-status.enum'
export interface UninstallLibraryInput {
  input?: {
    cluster_id?: string | null;
    id?: Array<number | null> | null;
  } | null;
}

export interface SelectionOnPackages {
  id: number | null;
}

export interface SelectionOnData {
  cluster_id: string | null;
  packages: Array<SelectionOnPackages | null> | null;
}

export interface SelectionOnUninstallLibrary {
  status: ApiStatus | null;
  message: string | null;
  data: SelectionOnData | null;
}

export interface UninstallLibrary {
  uninstallLibrary: SelectionOnUninstallLibrary | null;
}


export interface GraphQLWrapper {
  query: string
  name: string
  operation: OperationTypeNode
 }
export declare const GQL: GraphQLWrapper