/**
 * This file is autogenerated from gql:compile script using index.graphql .
 * Any changes made to this file will be overwritten in build.
 * It won't be committed into git.
 **/

import {OperationTypeNode} from 'graphql'

export interface GetWorkflowStatusInput {
  workflowId?: string | null;
}

export interface SelectionOnData {
  workflow_status: string | null;
}

export interface SelectionOnGetWorkflowDetails {
  data: SelectionOnData | null;
}

export interface GetWorkflowStatus {
  getWorkflowDetails: SelectionOnGetWorkflowDetails | null;
}

export interface GraphQLWrapper {
  query: string
  name: string
  operation: OperationTypeNode
 }
export declare const GQL: GraphQLWrapper