/**
 * This file is autogenerated from gql:compile script using index.graphql .
 * Any changes made to this file will be overwritten in build.
 * It won't be committed into git.
 **/

import {OperationTypeNode} from 'graphql'

export interface GetAllJobClustersV2Input {
  query?: string | null;
  pageSize?: number | null;
  offset?: number | null;
  sortBy?: string | null;
  sortOrder?: string | null;
  filters?: {
    user?: Array<string | null> | null;
    exclude_users?: Array<string | null> | null;
    status?: Array<string | null> | null;
    exclude_clusters?: Array<string | null> | null;
  } | null;
}

export interface SelectionOnData {
  job_cluster_definition_id: string | null;
  cluster_name: string | null;
  cores: number | null;
  memory: number | null;
  runtime: string | null;
  estimated_cost: string | null;
  created_at: string | null;
}

export interface SelectionOnGetAllJobClustersV2 {
  data: Array<SelectionOnData | null> | null;
  total_count: number | null;
}

export interface GetAllJobClustersV2 {
  getAllJobClustersV2: SelectionOnGetAllJobClustersV2 | null;
}

export interface GraphQLWrapper {
  query: string
  name: string
  operation: OperationTypeNode
 }
export declare const GQL: GraphQLWrapper