/**
 * This file is autogenerated from gql:compile script using getCountOfProjects.graphql .
 * Any changes made to this file will be overwritten in build.
 * It won't be committed into git.
 **/

import {OperationTypeNode} from 'graphql'

export interface SelectionOnData {
  my_projects: number | null;
  other_projects: number | null;
}

export interface SelectionOnGetCountOfProjects {
  status: string | null;
  data: SelectionOnData | null;
}

export interface GetCountOfProjects {
  getCountOfProjects: SelectionOnGetCountOfProjects | null;
}

export interface GraphQLWrapper {
  query: string
  name: string
  operation: OperationTypeNode
 }
export declare const GQL: GraphQLWrapper