/**
 * This file is autogenerated from gql:compile script using getActionGroupDetails.graphql .
 * Any changes made to this file will be overwritten in build.
 * It won't be committed into git.
 **/

import {OperationTypeNode} from 'graphql'

export interface GetActionGroupDetailsInput {
  clusterRuntimeId?: string | null;
  sortOrder?: string | null;
}

export interface SelectionOnData {
  timestamp: string | null;
  event_name: string | null;
  event_description: string | null;
}

export interface SelectionOnGetActionGroupDetails {
  status: string | null;
  data: Array<SelectionOnData | null> | null;
}

export interface GetActionGroupDetails {
  getActionGroupDetails: SelectionOnGetActionGroupDetails | null;
}

export interface GraphQLWrapper {
  query: string
  name: string
  operation: OperationTypeNode
 }
export declare const GQL: GraphQLWrapper