/**
 * This file is autogenerated from gql:compile script using getActionGroups.graphql .
 * Any changes made to this file will be overwritten in build.
 * It won't be committed into git.
 **/

import {OperationTypeNode} from 'graphql'

export interface GetActionGroupsInput {
  clusterId?: string | null;
  offset?: number | null;
  pageSize?: number | null;
  sortOrder?: string | null;
}

export interface SelectionOnFirstEvent {
  timestamp: string | null;
  event_name: string | null;
  event_description: string | null;
}

export interface SelectionOnLastEvent {
  timestamp: string | null;
  event_name: string | null;
  event_description: string | null;
}

export interface SelectionOnData {
  cluster_runtime_id: string | null;
  count_of_events: number | null;
  first_event: SelectionOnFirstEvent | null;
  last_event: SelectionOnLastEvent | null;
}

export interface SelectionOnGetActionGroups {
  status: string | null;
  data: Array<SelectionOnData | null> | null;
}

export interface GetActionGroups {
  getActionGroups: SelectionOnGetActionGroups | null;
}

export interface GraphQLWrapper {
  query: string
  name: string
  operation: OperationTypeNode
 }
export declare const GQL: GraphQLWrapper