/**
 * This file is autogenerated from gql:compile script using index.graphql .
 * Any changes made to this file will be overwritten in build.
 * It won't be committed into git.
 **/

import {OperationTypeNode} from 'graphql'

export interface SelectionOnData {
  last_run_time: string | null;
  status: string | null;
  workflow_id: string | null;
  workflow_name: string | null;
  display_name: string | null;
}

export interface SelectionOnGetRecentlyVisitedWorkflows {
  data: Array<SelectionOnData | null> | null;
}

export interface GetRecentlyVisitedWorkflows {
  getRecentlyVisitedWorkflows: SelectionOnGetRecentlyVisitedWorkflows | null;
}

export interface GraphQLWrapper {
  query: string
  name: string
  operation: OperationTypeNode
 }
export declare const GQL: GraphQLWrapper