/**
 * This file is autogenerated from gql:compile script using index.graphql .
 * Any changes made to this file will be overwritten in build.
 * It won't be committed into git.
 **/

import {OperationTypeNode} from 'graphql'

export interface SelectionOnData {
  status: Array<string | null> | null;
  users: Array<string | null> | null;
}

export interface SelectionOnGetWorkflowFilters {
  data: SelectionOnData | null;
}

export interface GetWorkflowFilters {
  getWorkflowFilters: SelectionOnGetWorkflowFilters | null;
}

export interface GraphQLWrapper {
  query: string
  name: string
  operation: OperationTypeNode
 }
export declare const GQL: GraphQLWrapper