export const SeverityTypes = {
  INFO: 'INFO',
  WARNING: 'WARNING',
  ERROR: 'ERROR'
}

export const EventTypes = {
  GENERIC: {
    LOGIN_OPEN: 'LOGIN_OPEN',
    UI_OPEN: 'UI_OPEN',
    UI_CLOSE: 'UI_CLOSE',
    ERROR: 'UI_ERROR'
  },
  COMPUTE: {
    LIST_OPEN: 'COMPUTE_LIST_OPEN',
    CREATE_OPEN: 'COMPUTE_CREATE_OPEN',
    DETAILS_OPEN: 'COMPUTE_DETAILS_OPEN'
  },
  WORKSPACE: {
    PAGE_OPEN: 'WORKSPACE_PAGE_OPEN'
  },
  FEATURE_STORE: {
    LIST_OPEN: 'FEATURE_STORE_LIST_OPEN',
    DETAILS_OPEN: 'FEATURE_STORE_DETAILS_OPEN'
  },
  WORKFLOWS: {
    LIST_OPEN: 'WORKFLOWS_LIST_OPEN',
    DETAILS_OPEN: 'WORKFLOWS_DETAILS_OPEN',
    CREATE_OPEN: 'WORKFLOWS_CREATE_OPEN',
    EDIT_OPEN: 'WORKFLOWS_EDIT_OPEN'
  },
  EXPERIMENTATION: {
    PAGE_OPEN: 'EXPERIMENTATION_PAGE_OPEN'
  },
  MODEL_REGISTRY: {
    PAGE_OPEN: 'MODEL_REGISTRY_PAGE_OPEN'
  },
  CUSTOM_RUNTIME: {
    LIST_OPEN: 'CUSTOM_RUNTIME_LIST_OPEN',
    DETAILS_OPEN: 'CUSTOM_RUNTIME_DETAILS_OPEN',
    CREATE_OPEN: 'CUSTOM_RUNTIME_CREATE_OPEN'
  }
}
