/**
 * This file is autogenerated from gql:compile script using index.graphql .
 * Any changes made to this file will be overwritten in build.
 * It won't be committed into git.
 **/

import {OperationTypeNode} from 'graphql'

export interface GetFeatureGroupsCountInput {
  searchString?: string | null;
  filters?: Array<{
    name?: string | null;
    value?: Array<string | null> | null;
  } | null> | null;
}

export interface SelectionOnData {
  offlineCount: number | null;
  onlineCount: number | null;
}

export interface SelectionOnGetFeatureGroupsCount {
  status: string | null;
  statusCode: number | null;
  data: SelectionOnData | null;
}

export interface GetFeatureGroupsCount {
  getFeatureGroupsCount: SelectionOnGetFeatureGroupsCount | null;
}

export interface GraphQLWrapper {
  query: string
  name: string
  operation: OperationTypeNode
 }
export declare const GQL: GraphQLWrapper