/**
 * This file is autogenerated from gql:compile script using index.graphql .
 * Any changes made to this file will be overwritten in build.
 * It won't be committed into git.
 **/

import {OperationTypeNode} from 'graphql'

export interface RunWorkflowRunInput {
  workflowId?: string | null;
  parameters?: any | null;
}

export interface SelectionOnLastRun {
  run_id: string | null;
  start_time: string | null;
  duration: number | null;
  run_status: string | null;
  trigger: string | null;
  trigger_by: string | null;
  is_run_duration_exceeded: boolean | null;
  expected_run_duration: number | null;
}

export interface SelectionOnData {
  workflow_id: string | null;
  last_runs_status: Array<string | null> | null;
  last_run: SelectionOnLastRun | null;
}

export interface SelectionOnRunWorkflowRun {
  data: SelectionOnData | null;
}

export interface RunWorkflowRun {
  runWorkflowRun: SelectionOnRunWorkflowRun | null;
}

export interface GraphQLWrapper {
  query: string
  name: string
  operation: OperationTypeNode
 }
export declare const GQL: GraphQLWrapper