/**
 * This file is autogenerated from gql:compile script using index.graphql .
 * Any changes made to this file will be overwritten in build.
 * It won't be committed into git.
 **/

import {OperationTypeNode} from 'graphql'

export interface ValidateModelDeploymentNameInput {
  deploymentName: string;
}

export interface SelectionOnData {
  unique: boolean | null;
}

export interface SelectionOnValidateModelDeploymentName {
  data: SelectionOnData;
}

export interface ValidateModelDeploymentName {
  validateModelDeploymentName: SelectionOnValidateModelDeploymentName | null;
}

export interface GraphQLWrapper {
  query: string
  name: string
  operation: OperationTypeNode
 }
export declare const GQL: GraphQLWrapper