/**
 * This file is autogenerated from gql:compile script using index.graphql .
 * Any changes made to this file will be overwritten in build.
 * It won't be committed into git.
 **/

import {OperationTypeNode} from 'graphql'

export interface GetSearchedClustersInput {
  query: string;
  sortBy: string;
  sortOrder: string;
  pageSize: number;
  offset: number;
  filters?: {
    status?: Array<string>;
    user?: Array<string>;
  } | null;
}

export interface SelectionOnCores {
  total: number | null;
  consumed: number | null;
}

export interface SelectionOnMemory {
  consumed: number | null;
  total: number | null;
}

export interface SelectionOnData {
  cluster_id: string | null;
  cluster_name: string | null;
  status: string | null;
  codespaces: number | null;
  runtime: string | null;
  cores: SelectionOnCores | null;
  memory: SelectionOnMemory | null;
  cost: number | null;
  tags: Array<string>;
  last_used_on: string | null;
  created_by: string | null;
  created_on: string | null;
}

export interface SelectionOnGetSearchedClusters {
  status: string | null;
  result_size: number | null;
  page_size: number | null;
  offset: number | null;
  data: Array<SelectionOnData>;
}

export interface GetSearchedClusters {
  getSearchedClusters: SelectionOnGetSearchedClusters | null;
}

export interface GraphQLWrapper {
  query: string
  name: string
  operation: OperationTypeNode
 }
export declare const GQL: GraphQLWrapper