/**
 * This file is autogenerated from gql:compile script using deleteCodespace.graphql .
 * Any changes made to this file will be overwritten in build.
 * It won't be committed into git.
 **/

import {OperationTypeNode} from 'graphql'

export interface DeleteCodespaceInput {
  projectId?: string | null;
  codespaceId?: string | null;
}

export interface SelectionOnData {
  codespace_id: number | null;
  project_id: number | null;
}

export interface SelectionOnDeleteCodespace {
  status: string | null;
  data: SelectionOnData | null;
}

export interface DeleteCodespace {
  deleteCodespace: SelectionOnDeleteCodespace | null;
}

export interface GraphQLWrapper {
  query: string
  name: string
  operation: OperationTypeNode
 }
export declare const GQL: GraphQLWrapper