/**
 * This file is autogenerated from gql:compile script using index.graphql .
 * Any changes made to this file will be overwritten in build.
 * It won't be committed into git.
 **/

import {OperationTypeNode} from 'graphql'

export interface CheckUniqueWorkflowInput {
  name?: string | null;
}

export interface SelectionOnData {
  unique: boolean | null;
}

export interface SelectionOnCheckUniqueWorkflow {
  data: SelectionOnData | null;
}

export interface CheckUniqueWorkflow {
  checkUniqueWorkflow: SelectionOnCheckUniqueWorkflow | null;
}

export interface GraphQLWrapper {
  query: string
  name: string
  operation: OperationTypeNode
 }
export declare const GQL: GraphQLWrapper