/**
 * This file is autogenerated from gql:compile script using index.graphql .
 * Any changes made to this file will be overwritten in build.
 * It won't be committed into git.
 **/

import {OperationTypeNode} from 'graphql'

export interface GetMLFlowModelVersionsInput {
  modelName: string;
}

export interface SelectionOnModelVersions {
  name: string | null;
  version: string | null;
  creation_timestamp: string | null;
  last_updated_timestamp: string | null;
  status: string | null;
  run_id: string | null;
}

export interface SelectionOnGetMLFlowModelVersions {
  model_versions: Array<SelectionOnModelVersions>;
}

export interface GetMLFlowModelVersions {
  getMLFlowModelVersions: SelectionOnGetMLFlowModelVersions | null;
}

export interface GraphQLWrapper {
  query: string
  name: string
  operation: OperationTypeNode
 }
export declare const GQL: GraphQLWrapper