/**
 * This file is autogenerated from gql:compile script using index.graphql .
 * Any changes made to this file will be overwritten in build.
 * It won't be committed into git.
 **/

import {OperationTypeNode} from 'graphql'
import {ModelDeploymentModelType} from '../../../../../gql-enums/model-deployment-model-type.enum'
import {CompatibleAppVersionStatus} from '../../../../../gql-enums/compatible-app-version-status.enum'
import {EventDataType} from '../../../../../gql-enums/event-data-type.enum'
export interface GetModelDeploymentForIdInput {
  deploymentId: string;
}

export interface SelectionOnCompatibleAppVersions {
  appName: string | null;
  codepushVersion: string | null;
  id: string | null;
  semver: string | null;
  buildNumber: number | null;
  createdAt: string | null;
  lastUpdatedAt: string | null;
  status: CompatibleAppVersionStatus | null;
}

export interface SelectionOnProps {
  defaultVal: string;
  propName: string;
  propNameMapping: string;
  sqlDataType: string;
}

export interface SelectionOnEventData {
  eventName: string;
  type: EventDataType;
  props: Array<SelectionOnProps>;
}

export interface SelectionOnEventTables {
  id: string | null;
  tableName: string;
  expiryInSecs: number | null;
  queries: Array<string>;
  eventData: SelectionOnEventData;
  version: string | null;
}

export interface SelectionOnFeatures {
  defaultVal: string;
  featureName: string;
  sqlDataType: string;
}

export interface SelectionOnFeatureGroupData {
  featureGroupName: string;
  features: Array<SelectionOnFeatures>;
}

export interface SelectionOnFeatureGroupTables {
  featureGroupData: SelectionOnFeatureGroupData;
  id: string | null;
  queries: Array<string>;
  tableName: string;
}

export interface SelectionOnData {
  id: string | null;
  deploymentName: string | null;
  modelType: ModelDeploymentModelType | null;
  modelName: string | null;
  mlFlowModel: string | null;
  mlFlowVersion: number | null;
  tags: Array<string>;
  configFilePath: string | null;
  testDataPath: string | null;
  modelArtifactPath: string | null;
  compatibleAppVersions: Array<SelectionOnCompatibleAppVersions>;
  eventTables: Array<SelectionOnEventTables>;
  featureGroupTables: Array<SelectionOnFeatureGroupTables | null> | null;
}

export interface SelectionOnGetModelDeploymentForId {
  data: SelectionOnData;
}

export interface GetModelDeploymentForId {
  getModelDeploymentForId: SelectionOnGetModelDeploymentForId | null;
}


export interface GraphQLWrapper {
  query: string
  name: string
  operation: OperationTypeNode
 }
export declare const GQL: GraphQLWrapper