/**
 * This file is autogenerated from gql:compile script using deleteProject.graphql .
 * Any changes made to this file will be overwritten in build.
 * It won't be committed into git.
 **/

import {OperationTypeNode} from 'graphql'

export interface DeleteProjectInput {
  projectId?: string | null;
}

export interface SelectionOnData {
  project_id: number | null;
}

export interface SelectionOnDeleteProject {
  status: string | null;
  data: SelectionOnData | null;
}

export interface DeleteProject {
  deleteProject: SelectionOnDeleteProject | null;
}

export interface GraphQLWrapper {
  query: string
  name: string
  operation: OperationTypeNode
 }
export declare const GQL: GraphQLWrapper