/**
 * This file is autogenerated from gql:compile script using checkUniqueProject.graphql .
 * Any changes made to this file will be overwritten in build.
 * It won't be committed into git.
 **/

import {OperationTypeNode} from 'graphql'

export interface CheckUniqueProjectInput {
  projectName?: string | null;
}

export interface SelectionOnData {
  is_unique: boolean | null;
}

export interface SelectionOnCheckUniqueProject {
  status: string | null;
  data: SelectionOnData | null;
}

export interface CheckUniqueProject {
  checkUniqueProject: SelectionOnCheckUniqueProject | null;
}

export interface GraphQLWrapper {
  query: string
  name: string
  operation: OperationTypeNode
 }
export declare const GQL: GraphQLWrapper