/**
 * This file is autogenerated from gql:compile script using getComputeInstanceRoles.graphql .
 * Any changes made to this file will be overwritten in build.
 * It won't be committed into git.
 **/

import {OperationTypeNode} from 'graphql'

export interface SelectionOnData {
  instance_role_id: string | null;
  display_name: string | null;
}

export interface SelectionOnGetComputeInstanceRoles {
  status: string | null;
  data: Array<SelectionOnData | null> | null;
}

export interface GetComputeInstanceRoles {
  getComputeInstanceRoles: SelectionOnGetComputeInstanceRoles | null;
}

export interface GraphQLWrapper {
  query: string
  name: string
  operation: OperationTypeNode
 }
export declare const GQL: GraphQLWrapper