/**
 * This file is autogenerated from gql:compile script using index.graphql .
 * Any changes made to this file will be overwritten in build.
 * It won't be committed into git.
 **/

import {OperationTypeNode} from 'graphql'

export interface GetWorkflowYamlInput {
  workflowId?: string | null;
}

export interface SelectionOnData {
  yaml: string | null;
  workflow_id: string | null;
}

export interface SelectionOnGetWorkflowYaml {
  data: SelectionOnData | null;
}

export interface GetWorkflowYaml {
  getWorkflowYaml: SelectionOnGetWorkflowYaml | null;
}

export interface GraphQLWrapper {
  query: string
  name: string
  operation: OperationTypeNode
 }
export declare const GQL: GraphQLWrapper