/**
 * This file is autogenerated from gql:compile script using getSampleDataForDataSource.graphql .
 * Any changes made to this file will be overwritten in build.
 * It won't be committed into git.
 **/

import {OperationTypeNode} from 'graphql'

export interface GetSampleDataForDataSourceInput {
  env?: string | null;
  source?: string | null;
  dataSource?: string | null;
  version?: string | null;
  offset?: number | null;
  pageSize?: number | null;
}

export interface SelectionOnCopyCodeCommand {
  name: string | null;
  value: string | null;
}

export interface SelectionOnSampleData {
  column_name: string | null;
  type: string | null;
  sample_data: string | null;
}

export interface SelectionOnData {
  versions: Array<string | null> | null;
  result_size: number | null;
  copy_code_command: Array<SelectionOnCopyCodeCommand | null> | null;
  sample_data: Array<SelectionOnSampleData | null> | null;
}

export interface SelectionOnGetSampleDataForDataSource {
  status: string | null;
  message: string | null;
  data: SelectionOnData | null;
}

export interface GetSampleDataForDataSource {
  getSampleDataForDataSource: SelectionOnGetSampleDataForDataSource | null;
}

export interface GraphQLWrapper {
  query: string
  name: string
  operation: OperationTypeNode
 }
export declare const GQL: GraphQLWrapper