/**
 * This file is autogenerated from gql:compile script using getComputeLimits.graphql .
 * Any changes made to this file will be overwritten in build.
 * It won't be committed into git.
 **/

import {OperationTypeNode} from 'graphql'

export interface SelectionOnCores {
  max: number | null;
  min: number | null;
}

export interface SelectionOnMemory {
  min: number | null;
  max: number | null;
}

export interface SelectionOnHeadNodeLimits {
  cores: SelectionOnCores | null;
  memory: SelectionOnMemory | null;
}

export interface SelectionOnCores1 {
  min: number | null;
  max: number | null;
}

export interface SelectionOnPods {
  min: number | null;
}

export interface SelectionOnWorkerNodeLimits {
  cores: SelectionOnCores1 | null;
  memory: SelectionOnMemory | null;
  pods: SelectionOnPods | null;
}

export interface SelectionOnInactiveTimeLimits {
  min: number | null;
}

export interface SelectionOnData {
  head_node_limits: SelectionOnHeadNodeLimits | null;
  worker_node_limits: SelectionOnWorkerNodeLimits | null;
  inactive_time_limits: SelectionOnInactiveTimeLimits | null;
}

export interface SelectionOnGetComputeLimits {
  status: string | null;
  data: SelectionOnData | null;
}

export interface GetComputeLimits {
  getComputeLimits: SelectionOnGetComputeLimits | null;
}

export interface GraphQLWrapper {
  query: string
  name: string
  operation: OperationTypeNode
 }
export declare const GQL: GraphQLWrapper