/**
 * This file is autogenerated from gql:compile script using index.graphql .
 * Any changes made to this file will be overwritten in build.
 * It won't be committed into git.
 **/

import {OperationTypeNode} from 'graphql'

export interface StopWorkflowRunInput {
  workflowId?: string | null;
  runId?: string | null;
}

export interface SelectionOnData {
  workflow_id: string | null;
  run_id: string | null;
  run_status: string | null;
}

export interface SelectionOnStopWorkflowRun {
  data: SelectionOnData | null;
}

export interface StopWorkflowRun {
  stopWorkflowRun: SelectionOnStopWorkflowRun | null;
}

export interface GraphQLWrapper {
  query: string
  name: string
  operation: OperationTypeNode
 }
export declare const GQL: GraphQLWrapper