/**
 * This file is autogenerated from gql:compile script using getAllClusters.graphql .
 * Any changes made to this file will be overwritten in build.
 * It won't be committed into git.
 **/

import {OperationTypeNode} from 'graphql'

export interface GetAllClustersInput {
  searchString?: string | null;
  pageSize?: number | null;
  offset?: number | null;
}

export interface SelectionOnData {
  cores: string | null;
  id: string | null;
  memory: string | null;
  name: string | null;
  status: string | null;
}

export interface SelectionOnGetAllClusters {
  status: string | null;
  data: Array<SelectionOnData | null> | null;
  offset: number | null;
  pageSize: number | null;
  resultSize: number | null;
}

export interface GetAllClusters {
  getAllClusters: SelectionOnGetAllClusters | null;
}

export interface GraphQLWrapper {
  query: string
  name: string
  operation: OperationTypeNode
 }
export declare const GQL: GraphQLWrapper