/**
 * This file is autogenerated from gql:compile script using updateComputeClusterTags.graphql .
 * Any changes made to this file will be overwritten in build.
 * It won't be committed into git.
 **/

import {OperationTypeNode} from 'graphql'

export interface UpdateComputeClusterTagsInput {
  input?: {
    clusterId?: string | null;
    data?: any | null;
  } | null;
}

export interface SelectionOnData {
  tags: Array<string | null> | null;
  cluster_id: string | null;
}

export interface SelectionOnUpdateComputeClusterTags {
  status: string | null;
  data: SelectionOnData | null;
}

export interface UpdateComputeClusterTags {
  updateComputeClusterTags: SelectionOnUpdateComputeClusterTags | null;
}

export interface GraphQLWrapper {
  query: string
  name: string
  operation: OperationTypeNode
 }
export declare const GQL: GraphQLWrapper