/**
 * This file is autogenerated from gql:compile script using index.graphql .
 * Any changes made to this file will be overwritten in build.
 * It won't be committed into git.
 **/

import {OperationTypeNode} from 'graphql'
import {ApiStatus} from '../../../../../gql-enums/api-status.enum'
import {LibraryStatus} from '../../../../../gql-enums/library-status.enum'
import {LibraryFileType} from '../../../../../gql-enums/library-file-type.enum'
export interface GetComputeLibrariesInput {
  key?: string | null;
  pageSize?: number | null;
  offset?: number | null;
  sortBy?: string | null;
  sortOrder?: string | null;
  cluster_id?: string | null;
}

export interface SelectionOnPackages {
  id: number | null;
  status: LibraryStatus | null;
  name: string | null;
  type: LibraryFileType | null;
  source: string | null;
  version: string | null;
}

export interface SelectionOnData {
  cluster_id: string | null;
  result_size: number | null;
  packages: Array<SelectionOnPackages | null> | null;
}

export interface SelectionOnGetComputeLibraries {
  status: ApiStatus | null;
  message: string | null;
  data: SelectionOnData | null;
}

export interface GetComputeLibraries {
  getComputeLibraries: SelectionOnGetComputeLibraries | null;
}


export interface GraphQLWrapper {
  query: string
  name: string
  operation: OperationTypeNode
 }
export declare const GQL: GraphQLWrapper