/**
 * This file is autogenerated from gql:compile script using index.graphql .
 * Any changes made to this file will be overwritten in build.
 * It won't be committed into git.
 **/

import {OperationTypeNode} from 'graphql'

export interface GetEventSchemaInput {
  appVersionId?: string | null;
}

export interface SelectionOnAndroidfull {
  name: string;
  expectedValue: string;
  rawDataType: string;
}

export interface SelectionOnIos {
  name: string;
  expectedValue: string;
  rawDataType: string;
}

export interface SelectionOnGlobalProperties {
  androidfull: Array<SelectionOnAndroidfull | null> | null;
  ios: Array<SelectionOnIos | null> | null;
}

export interface SelectionOnPropertyMetadata {
  expectedValue: string | null;
  name: string | null;
  rawDataType: string | null;
}

export interface SelectionOnAndroidfull1 {
  eventName: string | null;
  platform: string | null;
  propertyMetadata: Array<SelectionOnPropertyMetadata | null> | null;
}

export interface SelectionOnIos1 {
  eventName: string | null;
  platform: string | null;
  propertyMetadata: Array<SelectionOnPropertyMetadata | null> | null;
}

export interface SelectionOnMetadata {
  androidfull: SelectionOnAndroidfull1 | null;
  ios: SelectionOnIos1 | null;
}

export interface SelectionOnEvents {
  metadata: SelectionOnMetadata | null;
}

export interface SelectionOnData {
  globalProperties: SelectionOnGlobalProperties | null;
  events: Array<SelectionOnEvents>;
}

export interface SelectionOnGetEventSchema {
  data: SelectionOnData;
}

export interface GetEventSchema {
  getEventSchema: SelectionOnGetEventSchema | null;
}

export interface GraphQLWrapper {
  query: string
  name: string
  operation: OperationTypeNode
 }
export declare const GQL: GraphQLWrapper