/**
 * This file is autogenerated from gql:compile script using index.graphql .
 * Any changes made to this file will be overwritten in build.
 * It won't be committed into git.
 **/

import {OperationTypeNode} from 'graphql'

export interface CheckUniqueJobClusterNameInput {
  clusterName?: string | null;
}

export interface SelectionOnData {
  is_unique: boolean | null;
}

export interface SelectionOnCheckUniqueJobClusterName {
  data: SelectionOnData | null;
}

export interface CheckUniqueJobClusterName {
  checkUniqueJobClusterName: SelectionOnCheckUniqueJobClusterName | null;
}

export interface GraphQLWrapper {
  query: string
  name: string
  operation: OperationTypeNode
 }
export declare const GQL: GraphQLWrapper