/**
 * This file is autogenerated from gql:compile script using index.graphql .
 * Any changes made to this file will be overwritten in build.
 * It won't be committed into git.
 **/

import {OperationTypeNode} from 'graphql'

export interface GetWorkflowPathIdsInput {
  workspacePath: string;
}

export interface SelectionOnData {
  codespace_id: number | null;
  project_id: number | null;
}

export interface SelectionOnGetWorkflowPathDetails {
  data: SelectionOnData | null;
}

export interface GetWorkflowPathIds {
  getWorkflowPathDetails: SelectionOnGetWorkflowPathDetails | null;
}

export interface GraphQLWrapper {
  query: string
  name: string
  operation: OperationTypeNode
 }
export declare const GQL: GraphQLWrapper