/**
 * This file is autogenerated from gql:compile script using getComputeTemplates.graphql .
 * Any changes made to this file will be overwritten in build.
 * It won't be committed into git.
 **/

import {OperationTypeNode} from 'graphql'

export interface SelectionOnData {
  template_id: string | null;
  display_name: string | null;
  memory_per_core: string | null;
}

export interface SelectionOnGetComputeTemplates {
  status: string | null;
  data: Array<SelectionOnData | null> | null;
}

export interface GetComputeTemplates {
  getComputeTemplates: SelectionOnGetComputeTemplates | null;
}

export interface GraphQLWrapper {
  query: string
  name: string
  operation: OperationTypeNode
 }
export declare const GQL: GraphQLWrapper