/**
 * This file is autogenerated from gql:compile script using index.graphql .
 * Any changes made to this file will be overwritten in build.
 * It won't be committed into git.
 **/

import {OperationTypeNode} from 'graphql'

export interface UpdateWorkflowScheduleInput {
  workflowId?: string | null;
  schedule?: string | null;
}

export interface SelectionOnData {
  workflow_id: string | null;
  schedule: string | null;
}

export interface SelectionOnUpdateWorkflowSchedule {
  data: SelectionOnData | null;
}

export interface UpdateWorkflowSchedule {
  updateWorkflowSchedule: SelectionOnUpdateWorkflowSchedule | null;
}

export interface GraphQLWrapper {
  query: string
  name: string
  operation: OperationTypeNode
 }
export declare const GQL: GraphQLWrapper