/**
 * This file is autogenerated from gql:compile script using getClusterResources.graphql .
 * Any changes made to this file will be overwritten in build.
 * It won't be committed into git.
 **/

import {OperationTypeNode} from 'graphql'

export interface GetClusterResourcesInput {
  clusterId?: string | null;
}

export interface SelectionOnData {
  cores_used: number | null;
  memory_used: number | null;
}

export interface SelectionOnGetClusterResources {
  status: string | null;
  data: SelectionOnData | null;
  message: string | null;
}

export interface GetClusterResources {
  getClusterResources: SelectionOnGetClusterResources | null;
}

export interface GraphQLWrapper {
  query: string
  name: string
  operation: OperationTypeNode
 }
export declare const GQL: GraphQLWrapper