/**
 * This file is autogenerated from gql:compile script using index.graphql .
 * Any changes made to this file will be overwritten in build.
 * It won't be committed into git.
 **/

import {OperationTypeNode} from 'graphql'

export interface ValidateEdgeTableNameInput {
  tableName: string;
}

export interface SelectionOnData {
  tableNameExists: boolean | null;
}

export interface SelectionOnValidateEdgeTableName {
  data: SelectionOnData | null;
}

export interface ValidateEdgeTableName {
  validateEdgeTableName: SelectionOnValidateEdgeTableName | null;
}

export interface GraphQLWrapper {
  query: string
  name: string
  operation: OperationTypeNode
 }
export declare const GQL: GraphQLWrapper