/**
 * This file is autogenerated from gql:compile script using detachCluster.graphql .
 * Any changes made to this file will be overwritten in build.
 * It won't be committed into git.
 **/

import {OperationTypeNode} from 'graphql'

export interface DetachClusterInput {
  codespaceId?: string | null;
  clusterId?: string | null;
}

export interface SelectionOnDetachCluster {
  status: string | null;
}

export interface DetachCluster {
  detachCluster: SelectionOnDetachCluster | null;
}

export interface GraphQLWrapper {
  query: string
  name: string
  operation: OperationTypeNode
 }
export declare const GQL: GraphQLWrapper