/**
 * This file is autogenerated from gql:compile script using index.graphql .
 * Any changes made to this file will be overwritten in build.
 * It won't be committed into git.
 **/

import {OperationTypeNode} from 'graphql'
import {ApiStatus} from '../../../../gql-enums/api-status.enum'
export interface GetFeatureCopyCodesInput {
  featureTitles?: Array<string | null> | null;
  featureDataSourceId?: string | null;
  featureGroupName?: string | null;
}

export interface SelectionOnGetFeatureCopyCodes {
  data: string | null;
  status: ApiStatus | null;
  statusCode: number | null;
}

export interface GetFeatureCopyCodes {
  getFeatureCopyCodes: SelectionOnGetFeatureCopyCodes | null;
}


export interface GraphQLWrapper {
  query: string
  name: string
  operation: OperationTypeNode
 }
export declare const GQL: GraphQLWrapper