/**
 * This file is autogenerated from gql:compile script using graphql.schema.json .
 * Any changes made to this file will be overwritten in build.
 * It won't be committed into git.
 **/

export const enum LibraryType {
  JAR = 'JAR',
  WHL = 'WHL',
  ZIP = 'ZIP',
  TAR = 'TAR',
  GZ = 'GZ',
  TXT = 'TXT'
}
