/**
 * This file is autogenerated from gql:compile script using graphql.schema.json .
 * Any changes made to this file will be overwritten in build.
 * It won't be committed into git.
 **/

export const enum LibrariesFileType {
  WHEEL = 'WHEEL',
  JAR = 'JAR',
  MAVEN_JAR = 'MAVEN_JAR',
  PyPI = 'PyPI'
}
