/**
 * This file is autogenerated from gql:compile script using graphql.schema.json .
 * Any changes made to this file will be overwritten in build.
 * It won't be committed into git.
 **/

export const enum LibrarySource {
  s3 = 's3',
  pypi = 'pypi',
  maven = 'maven',
  darwin_artifactory = 'darwin_artifactory',
  workspace = 'workspace',
}
