/**
 * This file is autogenerated from gql:compile script using graphql.schema.json .
 * Any changes made to this file will be overwritten in build.
 * It won't be committed into git.
 **/

export const enum ModelDeploymentModelStatus {
  READY = 'READY',
  FAILED = 'FAILED',
  DEPLOYING = 'DEPLOYING',
  TESTING = 'TESTING',
  DEPLOYED = 'DEPLOYED',
  READY_TO_TEST = 'READY_TO_TEST',
}
