/**
 * This file is autogenerated from gql:compile script using graphql.schema.json .
 * Any changes made to this file will be overwritten in build.
 * It won't be committed into git.
 **/

export const enum ModelDeploymentSortOrder {
  asc = 'asc',
  desc = 'desc',
}
