/**
 * This file is autogenerated from gql:compile script using graphql.schema.json .
 * Any changes made to this file will be overwritten in build.
 * It won't be committed into git.
 **/

export const enum RuntimeType {
  RAY_ONLY = 'RAY_ONLY',
  RAY_AND_SPARK = 'RAY_AND_SPARK',
  CREATED_BY_ME = 'CREATED_BY_ME',
  CREATED_BY_OTHERS = 'CREATED_BY_OTHERS'
}
