/**
 * This file is autogenerated from gql:compile script using graphql.schema.json .
 * Any changes made to this file will be overwritten in build.
 * It won't be committed into git.
 **/

export const enum TriggerRules {
  all_success = 'all_success',
  all_failed = 'all_failed',
  all_done = 'all_done',
  all_skipped = 'all_skipped',
  one_failed = 'one_failed',
  one_success = 'one_success',
  one_done = 'one_done',
  none_failed = 'none_failed',
  none_failed_min_one_success = 'none_failed_min_one_success',
  none_skipped = 'none_skipped',
  always = 'always',
}
