/**
 * This file is autogenerated from gql:compile script using updateComputeCluster.graphql .
 * Any changes made to this file will be overwritten in build.
 * It won't be committed into git.
 **/

import {OperationTypeNode} from 'graphql'

export interface UpdateComputeClusterInput {
  input?: {
    clusterId?: string | null;
    data?: any | null;
  } | null;
}

export interface SelectionOnData {
  ClusterName: string | null;
  DashboardLink: string | null;
  JupyterLink: string | null;
}

export interface SelectionOnUpdateComputeCluster {
  status: string | null;
  data: SelectionOnData | null;
}

export interface UpdateComputeCluster {
  updateComputeCluster: SelectionOnUpdateComputeCluster | null;
}

export interface GraphQLWrapper {
  query: string
  name: string
  operation: OperationTypeNode
 }
export declare const GQL: GraphQLWrapper