/**
 * This file is autogenerated from gql:compile script using index.graphql .
 * Any changes made to this file will be overwritten in build.
 * It won't be committed into git.
 **/

import {OperationTypeNode} from 'graphql'

export interface GetLogGroupsInput {
  clusterId: string;
}

export interface SelectionOnData {
  session_id: string | null;
  start_timestamp: string | null;
  end_timestamp: string | null;
}

export interface SelectionOnGetLogGroups {
  data: Array<SelectionOnData | null> | null;
}

export interface GetLogGroups {
  getLogGroups: SelectionOnGetLogGroups | null;
}

export interface GraphQLWrapper {
  query: string
  name: string
  operation: OperationTypeNode
 }
export declare const GQL: GraphQLWrapper