/**
 * This file is autogenerated from gql:compile script using index.graphql .
 * Any changes made to this file will be overwritten in build.
 * It won't be committed into git.
 **/

import {OperationTypeNode} from 'graphql'

export interface StartSparkHistoryServerInput {
  resource?: string | null;
  ttl?: number | null;
}

export interface SelectionOnData {
  server_id: string | null;
}

export interface SelectionOnStartSparkHistoryServer {
  status: string | null;
  data: SelectionOnData | null;
  message: string | null;
}

export interface StartSparkHistoryServer {
  startSparkHistoryServer: SelectionOnStartSparkHistoryServer | null;
}

export interface GraphQLWrapper {
  query: string
  name: string
  operation: OperationTypeNode
 }
export declare const GQL: GraphQLWrapper