/**
 * This file is autogenerated from gql:compile script using index.graphql .
 * Any changes made to this file will be overwritten in build.
 * It won't be committed into git.
 **/

import {OperationTypeNode} from 'graphql'

export interface GetAllPurposeClustersInput {
  query?: string | null;
  pageSize?: number | null;
  offset?: number | null;
  sortBy?: string | null;
  sortOrder?: string | null;
  filters?: {
    user?: Array<string | null> | null;
  } | null;
  excludeFilters?: {
    user?: Array<string | null> | null;
  } | null;
}

export interface SelectionOnData {
  cluster_id: string | null;
  name: string | null;
  status: string | null;
  total_cores: number | null;
  total_memory: number | null;
  runtime: string | null;
  created_on: string | null;
  last_used_on: string | null;
  create_by: string | null;
  estimated_cost: string | null;
}

export interface SelectionOnGetAllPurposeClusters {
  status: string | null;
  result_size: number | null;
  page_size: number | null;
  offset: number | null;
  data: Array<SelectionOnData | null> | null;
}

export interface GetAllPurposeClusters {
  getAllPurposeClusters: SelectionOnGetAllPurposeClusters | null;
}

export interface GraphQLWrapper {
  query: string
  name: string
  operation: OperationTypeNode
 }
export declare const GQL: GraphQLWrapper