/**
 * This file is autogenerated from gql:compile script using index.graphql .
 * Any changes made to this file will be overwritten in build.
 * It won't be committed into git.
 **/

import {OperationTypeNode} from 'graphql'
import {RuntimeStatus} from '../../../../../gql-enums/runtime-status.enum'
export interface GetRuntimesStatusInput {
  query: string;
  pageSize: number;
  offset: number;
  sortBy?: string | null;
  sortOrder?: string | null;
}

export interface SelectionOnData {
  name: string;
  status: RuntimeStatus;
}

export interface SelectionOnGetRuntimesInformation {
  total_records: number;
  page_size: number;
  offset: number;
  data: Array<SelectionOnData>;
}

export interface GetRuntimesStatus {
  getRuntimesInformation: SelectionOnGetRuntimesInformation | null;
}


export interface GraphQLWrapper {
  query: string
  name: string
  operation: OperationTypeNode
 }
export declare const GQL: GraphQLWrapper