/**
 * This file is autogenerated from gql:compile script using index.graphql .
 * Any changes made to this file will be overwritten in build.
 * It won't be committed into git.
 **/

import {OperationTypeNode} from 'graphql'

export interface SelectionOnData {
  name: string | null;
  cores: number | null;
  memory: number | null;
  gpu_count: number | null;
  g_ram_memory: number | null;
  g_ram_type: string | null;
}

export interface SelectionOnGetComputeGpuPods {
  status: string | null;
  data: Array<SelectionOnData | null> | null;
}

export interface GetComputeGpuPods {
  getComputeGpuPods: SelectionOnGetComputeGpuPods | null;
}

export interface GraphQLWrapper {
  query: string
  name: string
  operation: OperationTypeNode
 }
export declare const GQL: GraphQLWrapper