/**
 * This file is autogenerated from gql:compile script using index.graphql .
 * Any changes made to this file will be overwritten in build.
 * It won't be committed into git.
 **/

import {OperationTypeNode} from 'graphql'
import {TriggerRules} from '../../../../gql-enums/trigger-rules.enum'
export interface GetWorkflowsMetaDataInput {
  names?: Array<string | null> | null;
}

export interface SelectionOnTriggerRules {
  id: number | null;
  label: string | null;
  value: TriggerRules | null;
  description: string | null;
}

export interface SelectionOnData {
  trigger_rules: Array<SelectionOnTriggerRules | null> | null;
}

export interface SelectionOnGetWorkflowsMetaData {
  status: string | null;
  message: string | null;
  data: SelectionOnData | null;
}

export interface GetWorkflowsMetaData {
  getWorkflowsMetaData: SelectionOnGetWorkflowsMetaData | null;
}


export interface GraphQLWrapper {
  query: string
  name: string
  operation: OperationTypeNode
 }
export declare const GQL: GraphQLWrapper