/**
 * This file is autogenerated from gql:compile script using index.graphql .
 * Any changes made to this file will be overwritten in build.
 * It won't be committed into git.
 **/

import {OperationTypeNode} from 'graphql'

export interface UpdateWorkflowRetriesInput {
  workflowId?: string | null;
  retries?: number | null;
}

export interface SelectionOnData {
  workflow_id: string | null;
  retries: number | null;
}

export interface SelectionOnUpdateWorkflowRetries {
  data: SelectionOnData | null;
}

export interface UpdateWorkflowRetries {
  updateWorkflowRetries: SelectionOnUpdateWorkflowRetries | null;
}

export interface GraphQLWrapper {
  query: string
  name: string
  operation: OperationTypeNode
 }
export declare const GQL: GraphQLWrapper