/**
 * This file is autogenerated from gql:compile script using index.graphql .
 * Any changes made to this file will be overwritten in build.
 * It won't be committed into git.
 **/

import {OperationTypeNode} from 'graphql'

export interface SelectionOnData {
  cluster_id: string | null;
  cluster_name: string | null;
  status: string | null;
  total_cores: number | null;
  total_memory: number | null;
  last_visited: string | null;
}

export interface SelectionOnGetRecentlyVisitedClusters {
  status: string | null;
  data: Array<SelectionOnData>;
}

export interface GetRecentlyVisitedClusters {
  getRecentlyVisitedClusters: SelectionOnGetRecentlyVisitedClusters | null;
}

export interface GraphQLWrapper {
  query: string
  name: string
  operation: OperationTypeNode
 }
export declare const GQL: GraphQLWrapper