/**
 * This file is autogenerated from gql:compile script using index.graphql .
 * Any changes made to this file will be overwritten in build.
 * It won't be committed into git.
 **/

import {OperationTypeNode} from 'graphql'

export interface GetLineageAssetInput {
  assetName: string;
}

export interface SelectionOnGraph {
  from: string | null;
  to: string | null;
  fields_map: any | null;
}

export interface SelectionOnGetLineageAsset {
  graph: Array<SelectionOnGraph | null> | null;
  assetsInfo: any | null;
}

export interface GetLineageAsset {
  getLineageAsset: SelectionOnGetLineageAsset | null;
}

export interface GraphQLWrapper {
  query: string
  name: string
  operation: OperationTypeNode
 }
export declare const GQL: GraphQLWrapper