/**
 * This file is autogenerated from gql:compile script using featureJobById.graphql .
 * Any changes made to this file will be overwritten in build.
 * It won't be committed into git.
 **/

import {OperationTypeNode} from 'graphql'

export interface FetchFeatureJobsByIdInput {
  featureJobId: string;
}

export interface SelectionOnConfig {
  featureGroup: string | null;
}

export interface SelectionOnDestinations {
  type: string | null;
  config: SelectionOnConfig | null;
}

export interface SelectionOnDataSourceConfigs {
  destinations: Array<SelectionOnDestinations | null> | null;
}

export interface SelectionOnDataSinkConfigs {
  destinations: Array<SelectionOnDestinations | null> | null;
}

export interface SelectionOnComputeMetadata {
  query: string | null;
}

export interface SelectionOnResponse {
  featureJobId: string | null;
  version: string | null;
  name: string | null;
  tags: Array<string | null> | null;
  descriptions: string | null;
  dataSourceConfigs: SelectionOnDataSourceConfigs | null;
  dataSinkConfigs: SelectionOnDataSinkConfigs | null;
  computeType: string | null;
  computeMetadata: SelectionOnComputeMetadata | null;
  featureType: string | null;
  schedule: string | null;
  owner: string | null;
  featureGroupId: number | null;
  schedulerId: number | null;
  createdAt: string | null;
  updatedAt: string | null;
  state: string | null;
}

export interface SelectionOnFetchFeatureJobsById {
  message: string | null;
  comments: string | null;
  response: Array<SelectionOnResponse | null> | null;
}

export interface FetchFeatureJobsById {
  fetchFeatureJobsById: SelectionOnFetchFeatureJobsById | null;
}

export interface GraphQLWrapper {
  query: string
  name: string
  operation: OperationTypeNode
 }
export declare const GQL: GraphQLWrapper