/**
 * This file is autogenerated from gql:compile script using fetchFilteredFeatureGroups.graphql .
 * Any changes made to this file will be overwritten in build.
 * It won't be committed into git.
 **/

import {OperationTypeNode} from 'graphql'

export interface FetchFilteredFeatureGroupsInput {
  query?: string | null;
  pageSize?: number | null;
  offset?: number | null;
  ownerEmail?: Array<string | null> | null;
  tags?: Array<string | null> | null;
  sortBy?: string | null;
  order?: string | null;
}

export interface SelectionOnFeatureGroups {
  name: string | null;
  version: number | null;
  ownerEmail: string | null;
  createdDate: string | null;
  status: string | null;
  description: string | null;
  tags: Array<string | null> | null;
}

export interface SelectionOnData {
  offset: number | null;
  pageSize: number | null;
  totalResults: number | null;
  featureGroups: Array<SelectionOnFeatureGroups | null> | null;
}

export interface SelectionOnFetchFilteredFeatureGroups {
  data: SelectionOnData | null;
}

export interface FetchFilteredFeatureGroups {
  fetchFilteredFeatureGroups: SelectionOnFetchFilteredFeatureGroups | null;
}

export interface GraphQLWrapper {
  query: string
  name: string
  operation: OperationTypeNode
 }
export declare const GQL: GraphQLWrapper