/**
 * This file is autogenerated from gql:compile script using filterList.graphql .
 * Any changes made to this file will be overwritten in build.
 * It won't be committed into git.
 **/

import {OperationTypeNode} from 'graphql'

export interface SelectionOnData {
  tags: Array<string | null> | null;
  owners: Array<string | null> | null;
}

export interface SelectionOnFetchAllFilters {
  message: string | null;
  data: SelectionOnData | null;
}

export interface FetchAllFilters {
  fetchAllFilters: SelectionOnFetchAllFilters | null;
}

export interface GraphQLWrapper {
  query: string
  name: string
  operation: OperationTypeNode
 }
export declare const GQL: GraphQLWrapper