/**
 * This file is autogenerated from gql:compile script using index.graphql .
 * Any changes made to this file will be overwritten in build.
 * It won't be committed into git.
 **/

import {OperationTypeNode} from 'graphql'

export interface GetDataForEnvironmentAndSourceInput {
  env?: string | null;
  source?: string | null;
  offset?: number | null;
  pageSize?: number | null;
  query?: string | null;
  database?: string | null;
}

export interface SelectionOnTables {
  table_id: string | null;
  dc_name: string | null;
  name: string | null;
  link: string | null;
  latest_version: string | null;
}

export interface SelectionOnData {
  result_size: number | null;
  tables: Array<SelectionOnTables | null> | null;
}

export interface SelectionOnGetDataForEnvironmentAndSource {
  status: string | null;
  data: SelectionOnData | null;
}

export interface GetDataForEnvironmentAndSource {
  getDataForEnvironmentAndSource: SelectionOnGetDataForEnvironmentAndSource | null;
}

export interface GraphQLWrapper {
  query: string
  name: string
  operation: OperationTypeNode
 }
export declare const GQL: GraphQLWrapper