/**
 * This file is autogenerated from gql:compile script using index.graphql .
 * Any changes made to this file will be overwritten in build.
 * It won't be committed into git.
 **/

import {OperationTypeNode} from 'graphql'

export interface UpdateWorkflowMaxConcurrentRunsInput {
  workflowId?: string | null;
  maxConcurrentRuns?: number | null;
}

export interface SelectionOnData {
  workflow_id: string | null;
  max_concurrent_runs: number | null;
}

export interface SelectionOnUpdateWorkflowMaxConcurrentRuns {
  data: SelectionOnData | null;
}

export interface UpdateWorkflowMaxConcurrentRuns {
  updateWorkflowMaxConcurrentRuns: SelectionOnUpdateWorkflowMaxConcurrentRuns | null;
}

export interface GraphQLWrapper {
  query: string
  name: string
  operation: OperationTypeNode
 }
export declare const GQL: GraphQLWrapper