/**
 * This file is autogenerated from gql:compile script using deleteJobClusterDefinition.graphql .
 * Any changes made to this file will be overwritten in build.
 * It won't be committed into git.
 **/

import {OperationTypeNode} from 'graphql'

export interface DeleteJobClusterDefinitionInput {
  input?: {
    cluster_id?: string | null;
  } | null;
}

export interface SelectionOnData {
  is_deleted: boolean | null;
  job_cluster_id: string | null;
}

export interface SelectionOnDeleteJobClusterDefinition {
  data: SelectionOnData | null;
}

export interface DeleteJobClusterDefinition {
  deleteJobClusterDefinition: SelectionOnDeleteJobClusterDefinition | null;
}

export interface GraphQLWrapper {
  query: string
  name: string
  operation: OperationTypeNode
 }
export declare const GQL: GraphQLWrapper