/**
 * This file is autogenerated from gql:compile script using fetchFeatureGroup.graphql .
 * Any changes made to this file will be overwritten in build.
 * It won't be committed into git.
 **/

import {OperationTypeNode} from 'graphql'

export interface FetchFeatureGroupInput {
  featureGroupName?: string | null;
  version?: number | null;
}

export interface SelectionOnS3 {
  location: string | null;
  referenceName: string | null;
  metadata: string | null;
}

export interface SelectionOnRedShift {
  location: string | null;
  referenceName: string | null;
  query: string | null;
}

export interface SelectionOnFeatureList {
  title: string | null;
  type: string | null;
}

export interface SelectionOnDataFeast {
  featureGroup: string | null;
  referenceName: string | null;
  featureList: Array<SelectionOnFeatureList | null> | null;
}

export interface SelectionOnAthena {
  tableName: string | null;
  datasetReferenceName: string | null;
  query: string | null;
}

export interface SelectionOnSources {
  s3: Array<SelectionOnS3 | null> | null;
  redShift: Array<SelectionOnRedShift | null> | null;
  dataFeast: Array<SelectionOnDataFeast | null> | null;
  athena: Array<SelectionOnAthena | null> | null;
}

export interface SelectionOnSinks {
  s3: Array<SelectionOnS3 | null> | null;
  redShift: Array<SelectionOnRedShift | null> | null;
  dataFeast: Array<SelectionOnDataFeast | null> | null;
  athena: Array<SelectionOnAthena | null> | null;
}

export interface SelectionOnCustomCode {
  s3ClassName: string | null;
  s3Path: string | null;
  requirementFilePath: string | null;
}

export interface SelectionOnComputeMetadata {
  computeType: string | null;
  sqlQuery: string | null;
  databricksLink: string | null;
  customCode: SelectionOnCustomCode | null;
}

export interface SelectionOnFeatures {
  name: string | null;
  type: string | null;
  tags: Array<string | null> | null;
  description: string | null;
  primaryKey: boolean | null;
  partitionKey: boolean | null;
}

export interface SelectionOnScheduleData {
  timeStamp: string | null;
  status: string | null;
  link: string | null;
  sampleData: string | null;
  errorStackTrack: string | null;
  retryNumber: string | null;
}

export interface SelectionOnScheduleJob {
  resourceTier: string | null;
  schedule: string | null;
  scheduleData: SelectionOnScheduleData | null;
}

export interface SelectionOnFeatureGroup {
  version: string | null;
  name: string | null;
  status: string | null;
  tags: Array<string | null> | null;
  description: string | null;
  slackNotificationChannel: string | null;
  sources: SelectionOnSources | null;
  sinks: SelectionOnSinks | null;
  computeMetadata: SelectionOnComputeMetadata | null;
  features: Array<SelectionOnFeatures | null> | null;
  scheduleJob: SelectionOnScheduleJob | null;
}

export interface SelectionOnData {
  featureGroup: SelectionOnFeatureGroup | null;
}

export interface SelectionOnFetchFeatureGroup {
  data: SelectionOnData | null;
}

export interface FetchFeatureGroup {
  fetchFeatureGroup: SelectionOnFetchFeatureGroup | null;
}

export interface GraphQLWrapper {
  query: string
  name: string
  operation: OperationTypeNode
 }
export declare const GQL: GraphQLWrapper