/**
 * This file is autogenerated from gql:compile script using getComputeDiscTypes.graphql .
 * Any changes made to this file will be overwritten in build.
 * It won't be committed into git.
 **/

import {OperationTypeNode} from 'graphql'

export interface SelectionOnGetComputeDiscTypes {
  status: string | null;
  data: Array<string | null> | null;
}

export interface GetComputeDiscTypes {
  getComputeDiscTypes: SelectionOnGetComputeDiscTypes | null;
}

export interface GraphQLWrapper {
  query: string
  name: string
  operation: OperationTypeNode
 }
export declare const GQL: GraphQLWrapper