/**
 * This file is autogenerated from gql:compile script using fetchFeatureGroupVersions.graphql .
 * Any changes made to this file will be overwritten in build.
 * It won't be committed into git.
 **/

import {OperationTypeNode} from 'graphql'

export interface FetchFeatureGroupVersionsInput {
  featureGroupName?: string | null;
}

export interface SelectionOnFeatureGroups {
  name: string | null;
  version: number | null;
  ownerEmail: string | null;
  createdDate: string | null;
  status: string | null;
  description: string | null;
  tags: Array<string | null> | null;
}

export interface SelectionOnData {
  featureGroups: Array<SelectionOnFeatureGroups | null> | null;
}

export interface SelectionOnFetchFeatureGroupVersions {
  data: SelectionOnData | null;
}

export interface FetchFeatureGroupVersions {
  fetchFeatureGroupVersions: SelectionOnFetchFeatureGroupVersions | null;
}

export interface GraphQLWrapper {
  query: string
  name: string
  operation: OperationTypeNode
 }
export declare const GQL: GraphQLWrapper