/**
 * This file is autogenerated from gql:compile script using index.graphql .
 * Any changes made to this file will be overwritten in build.
 * It won't be committed into git.
 **/

import {OperationTypeNode} from 'graphql'

export interface GetDatabasesForEnvironmentAndSourceInput {
  env?: string | null;
  source?: string | null;
  offset?: number | null;
  pageSize?: number | null;
  query?: string | null;
}

export interface SelectionOnDatabases {
  database_id: string | null;
  name: string | null;
  link: string | null;
}

export interface SelectionOnData {
  result_size: number | null;
  databases: Array<SelectionOnDatabases | null> | null;
}

export interface SelectionOnGetDatabasesForEnvironmentAndSource {
  status: string | null;
  data: SelectionOnData | null;
}

export interface GetDatabasesForEnvironmentAndSource {
  getDatabasesForEnvironmentAndSource: SelectionOnGetDatabasesForEnvironmentAndSource | null;
}

export interface GraphQLWrapper {
  query: string
  name: string
  operation: OperationTypeNode
 }
export declare const GQL: GraphQLWrapper