/**
 * This file is autogenerated from gql:compile script using searchComputeClusters.graphql .
 * Any changes made to this file will be overwritten in build.
 * It won't be committed into git.
 **/

import {OperationTypeNode} from 'graphql'

export interface SearchInput {
  searchQuery?: string | null;
  filters?: {
    status?: Array<string | null> | null;
  } | null;
  pageSize?: number | null;
  offset?: number | null;
  sortBy?: string | null;
  sortOrder?: string | null;
  filterByMe?: boolean | null;
}

export interface SelectionOnData {
  clusterId: string | null;
  clusterName: string | null;
  tags: Array<string | null> | null;
  status: string | null;
  runtime: string | null;
  activePod: number | null;
  totalPod: number | null;
  totalMemory: number | null;
  jupyterLabLink: string | null;
  createBy: string | null;
  createdOn: string | null;
  lastUsedOn: string | null;
}

export interface SelectionOnSearchComputeClusters {
  status: string | null;
  pageSize: number | null;
  offset: number | null;
  resultSize: number | null;
  data: Array<SelectionOnData | null> | null;
}

export interface Search {
  searchComputeClusters: SelectionOnSearchComputeClusters | null;
}

export interface GraphQLWrapper {
  query: string
  name: string
  operation: OperationTypeNode
 }
export declare const GQL: GraphQLWrapper