/**
 * This file is autogenerated from gql:compile script using getLastSyncTime.graphql .
 * Any changes made to this file will be overwritten in build.
 * It won't be committed into git.
 **/

import {OperationTypeNode} from 'graphql'

export interface GetLastSyncedTimeForCodespaceInput {
  codespaceId?: string | null;
}

export interface SelectionOnData {
  last_synced_time: string | null;
}

export interface SelectionOnGetLastSyncedTimeForCodespace {
  status: string | null;
  data: SelectionOnData | null;
}

export interface GetLastSyncedTimeForCodespace {
  getLastSyncedTimeForCodespace: SelectionOnGetLastSyncedTimeForCodespace | null;
}

export interface GraphQLWrapper {
  query: string
  name: string
  operation: OperationTypeNode
 }
export declare const GQL: GraphQLWrapper