export const globalTokens = {
  // neutral
  color_neutral_00: '#FFFFFF',
  color_neutral_10: '#F5F5F5',
  color_neutral_20: '#DADADA',
  color_neutral_30: '#C1C1C1',
  color_neutral_40: '#A8A8A8',
  color_neutral_50: '#8F8F8F',
  color_neutral_60: '#797979',
  color_neutral_70: '#666666',
  color_neutral_80: '#4D4D4D',
  color_neutral_90: '#333333',
  color_neutral_100: '#1A1A1A',
  color_neutral_110: '#121212',
  color_neutral_transparent: 'transparent',
  color_neutral_120: '#AFAFAF',
  color_neutral_130: '#D9D9D9',
  color_neutral_140: '#3333331A',
  color_neutral_150: '#1A1A1A99',
  color_neutral_160: '#d9d6d6',
  color_neutral_190: '#595959',
  color_neutral_220: '#757575',
  color_neutral_250: '#00000008',
  color_neutral_200: '#272727',
  color_neutral_300: '#565555',
  // red
  color_red_10: '#FFF0F0',
  color_red_20: '#FFE0E0',
  color_red_30: '#FFC9C9',
  color_red_40: '#FF9999',
  color_red_50: '#FF7070',
  color_red_60: '#E10000',
  color_red_70: '#B30000',
  color_red_80: '#8A0000',
  color_red_90: '#6B0000',
  color_red_100: '#540000',
  color_red_120: '#B20000',
  // blue
  color_blue_10: '#E9F4FF',
  color_blue_20: '#BADCFF',
  color_blue_30: '#8FC7FF',
  color_blue_40: '#74B9FF',
  color_blue_50: '#55AAFF',
  color_blue_60: '#399CFF',
  color_blue_70: '#007BF6',
  color_blue_80: '#0461BE',
  color_blue_90: '#034587',
  color_blue_100: '#022445',
  color_blue_transparent: 'rgb(0, 128, 255, 0.4)',
  color_blue_110: '#0080ff',
  color_blue_120: '#57ABFF',
  color_blue_130: '#1556B1',
  color_blue_140: '#337AB7',
  color_blue_150: '#0057AF',
  color_blue_160: '#0074E8',
  color_blue_170: '0057AD',
  color_blue_180: '#0057AD',
  color_blue_190: '#579DFF',
  color_blue_fade_60: 'rgb(87, 171, 255, 0.67)',
  color_blue_fade_20: 'rgb(87, 171, 255, 0.27)',
  // yellow
  color_yellow_10: '#FFF1D5',
  color_yellow_20: '#FFE2A7',
  color_yellow_30: '#FFD173',
  color_yellow_40: '#FFBB31',
  color_yellow_50: '#DD9400',
  color_yellow_60: '#B47902',
  color_yellow_70: '#8C6006',
  color_yellow_80: '#724F0A',
  color_yellow_90: '#5F4511',
  color_yellow_100: '#523A00',
  color_yellow_110: '#714E0A',
  color_yellow_120: '#DB9200',

  // green
  color_green_10: '#F0F9F3',
  color_green_20: '#C5E8CF',
  color_green_30: '#72D58E',
  color_green_40: '#38B75C',
  color_green_50: '#109E38',
  color_green_60: '#0D822E',
  color_green_70: '#0A6624',
  color_green_80: '#09531E',
  color_green_90: '#063C15',
  color_green_100: '#052E11',
  color_green_110: '#063f16',
  color_green_120: '#00b137',
  color_green_130: '#0F9535',
  // pink
  color_pink_10: '#FEDDE8',
  color_pink_20: '#F8C9D9',
  color_pink_30: '#F8B1C9',
  color_pink_40: '#F377A0',
  color_pink_50: '#FF4281',
  color_pink_60: '#E0004B',
  color_pink_70: '#B3053F',
  color_pink_80: '#990536',
  color_pink_90: '#83022D',
  color_pink_100: '#640223',
  color_pink_110: '#6d1b37',
  color_pink_120: '#FF075A',

  // pink
  color_orange_10: '#FEECE7',
  color_orange_20: '#FCD4CA',
  color_orange_30: '#F9A18B',
  color_orange_40: '#F77959',
  color_orange_50: '#F5552E',
  color_orange_60: '#E0350B',
  color_orange_70: '#C7300A',
  color_orange_80: '#A12608',
  color_orange_90: '#7F1E06',
  color_orange_100: '#531404',
  color_orange_110: '#B67A02',

  // teal
  color_teal_10: '#E6FCFF',
  color_teal_20: '#8FF0FF',
  color_teal_30: '#05DEFF',
  color_teal_40: '#00BAD6',
  color_teal_50: '#009BB3',
  color_teal_60: '#008599',
  color_teal_70: '#006A7A',
  color_teal_80: '#005966',
  color_teal_90: '#004A55',
  color_teal_100: '#003942',

  // purple
  color_purple_10: '#F9F6FE',
  color_purple_20: '#EAE0FC',
  color_purple_30: '#D8C8F4',
  color_purple_40: '#C6AEEF',
  color_purple_50: '#A781EA',
  color_purple_60: '#8962CB',
  color_purple_70: '#613D9E',
  color_purple_80: '#40266E',
  color_purple_90: '#23133F',
  color_purple_100: '#0D0618',
  color_purple_110: '#0224454d',
  color_purple_120: '#022445',
  color_purple_130: '#A781E9'
}

export const aliasTokens = {
  // Text colors
  base_text_color: globalTokens.color_neutral_00,
  ds_chip_default_text_color: globalTokens.color_neutral_10,
  primary_text_color: globalTokens.color_neutral_10,
  ds_filter_default_text_color: globalTokens.color_neutral_20,
  secondary_text_color: globalTokens.color_neutral_20,
  tertiary_text_color: globalTokens.color_neutral_50,
  information_text_color: globalTokens.color_purple_70,
  error_text_color: globalTokens.color_pink_120,
  success_text_color: globalTokens.color_green_60,
  warning_text_color: globalTokens.color_yellow_40,
  secondary_link_text_color: globalTokens.color_blue_70,
  disabled_text_color: globalTokens.color_neutral_70,
  subtitle_text_color: globalTokens.color_neutral_120,
  dialog_footer_text_color: globalTokens.color_green_120,
  validation_error_text_color: globalTokens.color_pink_60,
  neutral_text_color: globalTokens.color_neutral_130,
  label_text_color: globalTokens.color_neutral_160,
  label_text_color_new: globalTokens.color_neutral_80,
  ds_form_field_placeholder_color: globalTokens.color_neutral_50,
  ds_footer_text_color: globalTokens.color_neutral_220,
  duration_warning_text_color: globalTokens.color_yellow_120,
  // CTA Text color
  cta_primary_text_color: globalTokens.color_neutral_10,
  cta_secondary_text_color: globalTokens.color_blue_120,
  cta_tertiary_text_color: globalTokens.color_blue_50,
  cta_disabled_primary_text_color: globalTokens.color_neutral_90,
  cta_disabled_secondary_text_color: globalTokens.color_neutral_50,
  cta_disabled_tertiary_text_color: globalTokens.color_neutral_50,
  // CTA background color
  cta_primary_background_color: globalTokens.color_blue_70,
  cta_hover_primary_background_color: globalTokens.color_blue_80,
  cta_hover_secondary_background_color: globalTokens.color_blue_100,
  cta_hover_tertiary_background_color: globalTokens.color_blue_100,
  cta_secondary_background_color: globalTokens.color_neutral_transparent,
  cta_tertiary_background_color: globalTokens.color_blue_130,
  cta_disabled_primary_background_color: globalTokens.color_neutral_50,
  cta_disabled_secondary_background_color: globalTokens.color_neutral_80,
  cta_error_background_color: globalTokens.color_pink_80,
  cta_success_background_color: globalTokens.color_green_80,
  cta_success_inactive_background_color: globalTokens.color_green_90,
  cta_failed_background_color: globalTokens.color_red_80,
  cta_failed_inactive_background_color: globalTokens.color_red_90,
  // Background Colors
  primary_background_color: globalTokens.color_neutral_110,
  secondary_background_color: globalTokens.color_neutral_100,
  neutral_background_color: globalTokens.color_neutral_150,
  tertiary_background_color: globalTokens.color_neutral_90,
  information_background_color: globalTokens.color_purple_80,
  error_background_color: globalTokens.color_pink_80,
  error_tile_background_color: globalTokens.color_pink_80,
  success_background_color: globalTokens.color_green_80,
  success_tile_background_color: globalTokens.color_green_80,
  warning_background_color: globalTokens.color_yellow_80,
  pending_background_color: globalTokens.color_yellow_110,
  surface_background_color: globalTokens.color_neutral_80,
  active_background_color: globalTokens.color_green_50,
  purple_background_color: globalTokens.color_purple_110,
  table_popin_color: globalTokens.color_blue_140,
  switch_background_color: globalTokens.color_blue_170,
  ds_filter_item_active_background_color: globalTokens.color_neutral_130,
  ds_disabled_mui_field_background_color: globalTokens.color_neutral_250,

  // Border Color
  active_border_color: globalTokens.color_neutral_20,
  default_border_color: globalTokens.color_neutral_50,
  inactive_border_color: globalTokens.color_neutral_80,
  disabled_border_color: globalTokens.color_neutral_90,
  primary_border_color: globalTokens.color_blue_60, // for link & actionable items
  cta_primary_border_color: globalTokens.color_blue_60,
  cta_disabled_secondary_border_color: globalTokens.color_neutral_70,
  cta_error_border_color: globalTokens.color_pink_50,
  cta_error_border_color_2: globalTokens.color_red_60,
  cta_success_border_color: globalTokens.color_green_60,
  cta_success_border_color_2: globalTokens.color_green_130,
  cta_skipped_border_color: globalTokens.color_pink_40,
  information_border_color: globalTokens.color_yellow_40,
  error_border_color: globalTokens.color_pink_50,
  ds_form_field_border_color: globalTokens.color_neutral_50,
  success_border_color: globalTokens.color_green_60,
  warning_border_color: globalTokens.color_purple_70,
  purple_border_color: globalTokens.color_purple_120,
  blue_border_color: globalTokens.color_blue_150,
  blue_border_color_2: globalTokens.color_blue_160,
  checkbox_disabled_border_color: globalTokens.color_neutral_300,

  // hover
  hover_primary_color: globalTokens.color_blue_80,
  hover_secondary_color: globalTokens.color_blue_110,
  hover_neutral_color: globalTokens.color_neutral_130,
  hover_list_color: globalTokens.color_neutral_140,
  ds_chip_active_hover_background_color: globalTokens.color_blue_180,
  ds_chip_active_hover_text_color: globalTokens.color_neutral_10,
  // loader
  loader_primary_color: globalTokens.color_teal_30,

  // icons
  base_icon_color: globalTokens.color_neutral_00,
  disabled_icon_color: globalTokens.color_neutral_50,
  primary_icon_color: globalTokens.color_blue_70,
  secondary_icon_color: globalTokens.color_blue_50,
  tertiary_icon_color: globalTokens.color_blue_30,
  warning_icon_color: globalTokens.color_yellow_30,
  information_icon_color: globalTokens.color_purple_70,
  success_icon_color: globalTokens.color_green_30,
  error_icon_color: globalTokens.color_pink_30,
  warning_orange_icon_color: globalTokens.color_orange_110,
  warning_red_icon_color: globalTokens.color_red_50,
  info_purple_icon_color: globalTokens.color_purple_50,
  events_info_purple_icon_color: globalTokens.color_purple_130,
  dropdown_link_icon_color: globalTokens.color_blue_190,
  // cta icons
  cta_primary_icon_color: globalTokens.color_neutral_10,
  color_disabled_primary_icon_color: globalTokens.color_neutral_100,
  cta_secondary_icon_color: globalTokens.color_blue_50,
  cta_disabled_secondary_icon_color: globalTokens.color_neutral_50,
  cta_tertiary_icon_color: globalTokens.color_blue_50,
  cta_disabled_tertiary_icon_color: globalTokens.color_neutral_50,
  ds_ticker_error_icon_color: globalTokens.color_red_120,

  form_field_icon_color: globalTokens.color_neutral_130,
  date_range_filter_border_color: globalTokens.color_neutral_190,
  date_range_filter_background_color: globalTokens.color_neutral_90,
  date_range_filter_text_color: globalTokens.color_neutral_00,
  date_range_filter_active_color: globalTokens.color_neutral_80,
  date_range_filter_active_button_color: globalTokens.color_neutral_200
}

export const themeConfig = {
  fontFamily: ['Roboto', 'sans-serif'].join(',')
}
