/**
 * This file is autogenerated from gql:compile script using index.graphql .
 * Any changes made to this file will be overwritten in build.
 * It won't be committed into git.
 **/

import {OperationTypeNode} from 'graphql'
import {ApiStatus} from '../../../../gql-enums/api-status.enum'
export interface GetProdUsageListInput {
  featureGroupId?: string | null;
  featureTitle?: string | null;
  type?: string | null;
}

export interface SelectionOnData {
  type: string | null;
  title: string | null;
  link: string | null;
}

export interface SelectionOnGetProdUsageList {
  status: ApiStatus | null;
  statusCode: number | null;
  data: Array<SelectionOnData | null> | null;
}

export interface GetProdUsageList {
  getProdUsageList: SelectionOnGetProdUsageList | null;
}


export interface GraphQLWrapper {
  query: string
  name: string
  operation: OperationTypeNode
 }
export declare const GQL: GraphQLWrapper