/**
 * This file is autogenerated from gql:compile script using index.graphql .
 * Any changes made to this file will be overwritten in build.
 * It won't be committed into git.
 **/

import {OperationTypeNode} from 'graphql'

export interface GetMLFlowModelArtifactUrlInput {
  runId?: string | null;
}

export interface SelectionOnFiles {
  path: string;
  is_dir: boolean;
  file_size: number;
}

export interface SelectionOnGetMLFlowModelArtifactUrl {
  root_uri: string;
  files: Array<SelectionOnFiles>;
}

export interface GetMLFlowModelArtifactUrl {
  getMLFlowModelArtifactUrl: SelectionOnGetMLFlowModelArtifactUrl | null;
}

export interface GraphQLWrapper {
  query: string
  name: string
  operation: OperationTypeNode
 }
export declare const GQL: GraphQLWrapper