/**
 * This file is autogenerated from gql:compile script using index.graphql .
 * Any changes made to this file will be overwritten in build.
 * It won't be committed into git.
 **/

import {OperationTypeNode} from 'graphql'
import {LibraryStatus} from '../../../../../gql-enums/library-status.enum'
export interface GetComputeLibraryStatusesInput {
  cluster_id?: string | null;
  library_ids?: Array<number | null> | null;
}

export interface SelectionOnData {
  library_id: number | null;
  status: LibraryStatus | null;
}

export interface SelectionOnGetComputeLibraryStatuses {
  data: Array<SelectionOnData | null> | null;
}

export interface GetComputeLibraryStatuses {
  getComputeLibraryStatuses: SelectionOnGetComputeLibraryStatuses | null;
}


export interface GraphQLWrapper {
  query: string
  name: string
  operation: OperationTypeNode
 }
export declare const GQL: GraphQLWrapper