/**
 * This file is autogenerated from gql:compile script using index.graphql .
 * Any changes made to this file will be overwritten in build.
 * It won't be committed into git.
 **/

import {OperationTypeNode} from 'graphql'
import {ApiStatus} from '../../../../gql-enums/api-status.enum'
export interface GetFeatureGroupRunsInput {
  fg_name?: string | null;
  version?: number | null;
}

export interface SelectionOnOtherFactors {
  name: string | null;
  value: string | null;
}

export interface SelectionOnFeatures {
  title: string | null;
  otherFactors: Array<SelectionOnOtherFactors | null> | null;
  sampleData: Array<string | null> | null;
}

export interface SelectionOnData {
  status: ApiStatus | null;
  message: string | null;
  statusCode: number | null;
  executionTime: string | null;
  duration: number | null;
  link: string | null;
  totalRecordsCount: number | null;
  features: Array<SelectionOnFeatures | null> | null;
}

export interface SelectionOnGetFeatureGroupRuns {
  status: ApiStatus | null;
  statusCode: number | null;
  data: Array<SelectionOnData | null> | null;
  error: string | null;
}

export interface GetFeatureGroupRuns {
  getFeatureGroupRuns: SelectionOnGetFeatureGroupRuns | null;
}


export interface GraphQLWrapper {
  query: string
  name: string
  operation: OperationTypeNode
 }
export declare const GQL: GraphQLWrapper