/**
 * This file is autogenerated from gql:compile script using UpdateComputeClusterName.graphql .
 * Any changes made to this file will be overwritten in build.
 * It won't be committed into git.
 **/

import {OperationTypeNode} from 'graphql'

export interface UpdateComputeClusterNameInput {
  input?: {
    clusterId?: string | null;
    data?: any | null;
  } | null;
}

export interface SelectionOnData {
  name: string | null;
}

export interface SelectionOnUpdateComputeClusterName {
  status: string | null;
  data: SelectionOnData | null;
}

export interface UpdateComputeClusterName {
  updateComputeClusterName: SelectionOnUpdateComputeClusterName | null;
}

export interface GraphQLWrapper {
  query: string
  name: string
  operation: OperationTypeNode
 }
export declare const GQL: GraphQLWrapper