/**
 * This file is autogenerated from gql:compile script using index.graphql .
 * Any changes made to this file will be overwritten in build.
 * It won't be committed into git.
 **/

import {OperationTypeNode} from 'graphql'

export interface SelectionOnRegisteredModels {
  name: string | null;
  creation_timestamp: string | null;
  last_updated_timestamp: string | null;
}

export interface SelectionOnGetMLFlowRegisteredModels {
  registered_models: Array<SelectionOnRegisteredModels>;
}

export interface GetMLFlowRegisteredModels {
  getMLFlowRegisteredModels: SelectionOnGetMLFlowRegisteredModels | null;
}

export interface GraphQLWrapper {
  query: string
  name: string
  operation: OperationTypeNode
 }
export declare const GQL: GraphQLWrapper