/**
 * This file is autogenerated from gql:compile script using index.graphql .
 * Any changes made to this file will be overwritten in build.
 * It won't be committed into git.
 **/

import {OperationTypeNode} from 'graphql'

export interface GetAllCodespacesInput {
  clusterId: string;
  query: string;
  pageSize: number;
  offset: number;
  sortBy: string;
  sortOrder: string;
}

export interface SelectionOnCodespace {
  id: string;
  name: string;
}

export interface SelectionOnProject {
  id: string;
  name: string;
}

export interface SelectionOnCores {
  consumed: number;
  total: number;
}

export interface SelectionOnMemory {
  consumed: number;
  total: number;
}

export interface SelectionOnData {
  codespace: SelectionOnCodespace;
  project: SelectionOnProject;
  cores: SelectionOnCores;
  memory: SelectionOnMemory;
  attached_since: string;
  user: string;
}

export interface SelectionOnGetAllCodespaces {
  status: string;
  result_size: number;
  page_size: number;
  offset: number;
  data: Array<SelectionOnData>;
}

export interface GetAllCodespaces {
  getAllCodespaces: SelectionOnGetAllCodespaces;
}

export interface GraphQLWrapper {
  query: string
  name: string
  operation: OperationTypeNode
 }
export declare const GQL: GraphQLWrapper