/**
 * This file is autogenerated from gql:compile script using getComputeAvailabilityZones.graphql .
 * Any changes made to this file will be overwritten in build.
 * It won't be committed into git.
 **/

import {OperationTypeNode} from 'graphql'

export interface SelectionOnData {
  az_id: string | null;
  display_name: string | null;
}

export interface SelectionOnGetComputeAvailabilityZones {
  status: string | null;
  data: Array<SelectionOnData | null> | null;
}

export interface GetComputeAvailabilityZones {
  getComputeAvailabilityZones: SelectionOnGetComputeAvailabilityZones | null;
}

export interface GraphQLWrapper {
  query: string
  name: string
  operation: OperationTypeNode
 }
export declare const GQL: GraphQLWrapper