/**
 * This file is autogenerated from gql:compile script using index.graphql .
 * Any changes made to this file will be overwritten in build.
 * It won't be committed into git.
 **/

import {OperationTypeNode} from 'graphql'
import {ApiStatus} from '../../../../../gql-enums/api-status.enum'
export interface GetComputeRuntimeInput {
  search_query?: string | null;
  offset?: number | null;
  page_size?: number | null;
  class?: string | null;
  type?: string | null;
  is_deleted?: boolean | null;
}

export interface SelectionOnComponents {
  name: string | null;
  version: string | null;
}

export interface SelectionOnDefaultRuntime {
  id: number | null;
  class: string | null;
  type: string | null;
  runtime: string | null;
  image: string | null;
  reference_link: string | null;
  components: Array<SelectionOnComponents | null> | null;
  created_by: string | null;
  last_updated_by: string | null;
  created_at: string | null;
  last_updated_at: string | null;
  is_deleted: boolean | null;
  spark_connect: boolean | null;
  spark_auto_init: boolean | null;
}

export interface SelectionOnRuntimeList {
  id: number | null;
  class: string | null;
  type: string | null;
  runtime: string | null;
  image: string | null;
  reference_link: string | null;
  components: Array<SelectionOnComponents | null> | null;
  created_by: string | null;
  last_updated_by: string | null;
  created_at: string | null;
  last_updated_at: string | null;
  is_deleted: boolean | null;
  spark_auto_init: boolean | null;
  spark_connect: boolean | null;
}

export interface SelectionOnRuntimes {
  type: string | null;
  count: number | null;
  runtime_list: Array<SelectionOnRuntimeList | null> | null;
}

export interface SelectionOnData {
  class: string | null;
  default_runtime: SelectionOnDefaultRuntime | null;
  total_count: number | null;
  runtimes: Array<SelectionOnRuntimes | null> | null;
}

export interface SelectionOnGetComputeRuntime {
  status: ApiStatus | null;
  message: string | null;
  data: Array<SelectionOnData | null> | null;
}

export interface GetComputeRuntime {
  getComputeRuntime: SelectionOnGetComputeRuntime | null;
}


export interface GraphQLWrapper {
  query: string
  name: string
  operation: OperationTypeNode
 }
export declare const GQL: GraphQLWrapper