/**
 * This file is autogenerated from gql:compile script using getComputeRuntimeList.graphql .
 * Any changes made to this file will be overwritten in build.
 * It won't be committed into git.
 **/

import {OperationTypeNode} from 'graphql'

export interface SelectionOnGpu {
  name: string | null;
  created_by: string | null;
}

export interface SelectionOnCustom {
  name: string | null;
  created_by: string | null;
}

export interface SelectionOnCpu {
  name: string | null;
  created_by: string | null;
}

export interface SelectionOnOthers {
  name: string | null;
  created_by: string | null;
}

export interface SelectionOnData {
  gpu: Array<SelectionOnGpu | null> | null;
  custom: Array<SelectionOnCustom | null> | null;
  cpu: Array<SelectionOnCpu | null> | null;
  others: Array<SelectionOnOthers | null> | null;
}

export interface SelectionOnGetComputeRuntimeList {
  status: string | null;
  data: SelectionOnData | null;
}

export interface GetComputeRuntimeList {
  getComputeRuntimeList: SelectionOnGetComputeRuntimeList | null;
}

export interface GraphQLWrapper {
  query: string
  name: string
  operation: OperationTypeNode
 }
export declare const GQL: GraphQLWrapper