/**
 * This file is autogenerated from gql:compile script using index.graphql .
 * Any changes made to this file will be overwritten in build.
 * It won't be committed into git.
 **/

import {OperationTypeNode} from 'graphql'

export interface SelectionOnData {
  users: Array<string>;
  status: Array<string>;
}

export interface SelectionOnGetFilterOptions {
  status: string | null;
  data: SelectionOnData | null;
}

export interface GetFilterOptions {
  getFilterOptions: SelectionOnGetFilterOptions | null;
}

export interface GraphQLWrapper {
  query: string
  name: string
  operation: OperationTypeNode
 }
export declare const GQL: GraphQLWrapper