/**
 * This file is autogenerated from gql:compile script using index.graphql .
 * Any changes made to this file will be overwritten in build.
 * It won't be committed into git.
 **/

import {OperationTypeNode} from 'graphql'

export interface GetCatalogAssetsInput {
  regex?: string | null;
  page_size?: number | null;
  offset?: number | null;
}

export interface SelectionOnDetail {
  org: string | null;
  type: string | null;
  catalog_name: string | null;
  database_name: string | null;
  table_name: string | null;
}

export interface SelectionOnRules {
  id: number | null;
  schedule: string | null;
  left_expression: string | null;
  comparator: string | null;
  right_expression: string | null;
  health_status: boolean | null;
  type: string | null;
}

export interface SelectionOnImmediateParents {
  name: string | null;
  columnsMap: any | null;
}

export interface SelectionOnAssetSchema {
  version: number | null;
  schema_json: any | null;
}

export interface SelectionOnMetadata {
  path: string | null;
  type: string | null;
}

export interface SelectionOnAssets {
  fqdn: string | null;
  type: string | null;
  detail: SelectionOnDetail | null;
  description: string | null;
  source_platform: string | null;
  business_roster: string | null;
  rules: Array<SelectionOnRules | null> | null;
  quality_score: string | null;
  severity: string | null;
  slack_channel: string | null;
  immediate_parents: Array<SelectionOnImmediateParents | null> | null;
  tags: Array<string | null> | null;
  asset_schema: SelectionOnAssetSchema | null;
  asset_created_at: number | null;
  asset_updated_at: number | null;
  metadata: SelectionOnMetadata | null;
}

export interface SelectionOnGetCatalogAssets {
  total: number | null;
  offset: number | null;
  page_size: number | null;
  assets: Array<SelectionOnAssets | null> | null;
}

export interface GetCatalogAssets {
  getCatalogAssets: SelectionOnGetCatalogAssets | null;
}

export interface GraphQLWrapper {
  query: string
  name: string
  operation: OperationTypeNode
 }
export declare const GQL: GraphQLWrapper