/**
 * This file is autogenerated from gql:compile script using index.graphql .
 * Any changes made to this file will be overwritten in build.
 * It won't be committed into git.
 **/

import {OperationTypeNode} from 'graphql'

export interface SelectionOnData {
  id: number | null;
  label: string | null;
}

export interface SelectionOnGetLogComponents {
  data: Array<SelectionOnData | null> | null;
}

export interface GetLogComponents {
  getLogComponents: SelectionOnGetLogComponents | null;
}

export interface GraphQLWrapper {
  query: string
  name: string
  operation: OperationTypeNode
 }
export declare const GQL: GraphQLWrapper