/**
 * This file is autogenerated from gql:compile script using index.graphql .
 * Any changes made to this file will be overwritten in build.
 * It won't be committed into git.
 **/

import {OperationTypeNode} from 'graphql'
import {RepositoryType} from '../../../../gql-enums/repository-type.enum'
import {TriggerRules} from '../../../../gql-enums/trigger-rules.enum'
export interface GetWorkflowTaskDetailsWithoutRunInput {
  workflowId?: string | null;
  taskId?: string | null;
}

export interface SelectionOnMetadata {
  repository: RepositoryType | null;
  exclusions: string | null;
}

export interface SelectionOnBody {
  path: string | null;
  name: string | null;
  version: string | null;
  metadata: SelectionOnMetadata | null;
}

export interface SelectionOnPackages {
  source: string | null;
  body: SelectionOnBody | null;
}

export interface SelectionOnAttachedCluster {
  cluster_id: string | null;
  runtime: string | null;
  cluster_name: string | null;
  cluster_status: string | null;
  memory: number | null;
  cores: number | null;
  ray_dashboard: string | null;
  logs_dashboard: string | null;
  events_dashboard: string | null;
}

export interface SelectionOnNotificationPreference {
  on_fail: boolean | null;
}

export interface SelectionOnData {
  workflow_id: string | null;
  task_id: string | null;
  duration: number | null;
  source_type: string | null;
  file_path: string | null;
  dynamic_artifact: boolean | null;
  source: string | null;
  dependent_libraries: string | null;
  packages: Array<SelectionOnPackages | null> | null;
  depends_on: Array<string | null> | null;
  input_parameters: any | null;
  retries: number | null;
  timeout: number | null;
  attached_cluster: SelectionOnAttachedCluster | null;
  message: string | null;
  codespace_id: number | null;
  project_id: number | null;
  notify_on: string | null;
  trigger_rule: TriggerRules | null;
  notification_preference: SelectionOnNotificationPreference | null;
}

export interface SelectionOnGetWorkflowTaskDetailsWithoutRun {
  data: SelectionOnData | null;
}

export interface GetWorkflowTaskDetailsWithoutRun {
  getWorkflowTaskDetailsWithoutRun: SelectionOnGetWorkflowTaskDetailsWithoutRun | null;
}


export interface GraphQLWrapper {
  query: string
  name: string
  operation: OperationTypeNode
 }
export declare const GQL: GraphQLWrapper