/**
 * This file is autogenerated from gql:compile script using index.graphql .
 * Any changes made to this file will be overwritten in build.
 * It won't be committed into git.
 **/

import {OperationTypeNode} from 'graphql'
import {ApiStatus} from '../../../../gql-enums/api-status.enum'
export interface GetFeatureGroupDetailsInput {
  getFeatureGroupDetailsId?: string | null;
  version?: number | null;
  type?: string | null;
}

export interface SelectionOnCopyCode {
  name: string | null;
  value: string | null;
}

export interface SelectionOnSinks {
  location: string | null;
  type: string | null;
}

export interface SelectionOnData {
  id: string | null;
  title: string | null;
  description: string | null;
  version: number | null;
  allVersions: Array<number | null> | null;
  lastValueUpdated: string | null;
  createdBy: string | null;
  tags: Array<string | null> | null;
  type: string | null;
  typesAvailable: Array<string | null> | null;
  copyCode: Array<SelectionOnCopyCode | null> | null;
  sinks: Array<SelectionOnSinks | null> | null;
}

export interface SelectionOnGetFeatureGroupDetails {
  status: ApiStatus | null;
  statusCode: number | null;
  data: SelectionOnData | null;
}

export interface GetFeatureGroupDetails {
  getFeatureGroupDetails: SelectionOnGetFeatureGroupDetails | null;
}


export interface GraphQLWrapper {
  query: string
  name: string
  operation: OperationTypeNode
 }
export declare const GQL: GraphQLWrapper