/**
 * This file is autogenerated from gql:compile script using index.graphql .
 * Any changes made to this file will be overwritten in build.
 * It won't be committed into git.
 **/

import {OperationTypeNode} from 'graphql'

export interface ResumeWorkflowScheduleInput {
  workflowId?: string | null;
}

export interface SelectionOnData {
  workflow_id: string | null;
  workflow_status: string | null;
}

export interface SelectionOnResumeWorkflowSchedule {
  data: SelectionOnData | null;
}

export interface ResumeWorkflowSchedule {
  resumeWorkflowSchedule: SelectionOnResumeWorkflowSchedule | null;
}

export interface GraphQLWrapper {
  query: string
  name: string
  operation: OperationTypeNode
 }
export declare const GQL: GraphQLWrapper