/**
 * This file is autogenerated from gql:compile script using getProjects.graphql .
 * Any changes made to this file will be overwritten in build.
 * It won't be committed into git.
 **/

import {OperationTypeNode} from 'graphql'

export interface GetProjectsInput {
  query?: string | null;
  myProjects?: boolean | null;
  sortBy?: string | null;
  user?: string | null;
}

export interface SelectionOnData {
  project_id: string | null;
  project_name: string | null;
  number_of_codespaces: number | null;
  last_updated: string | null;
  created_on: string | null;
  created_by: string | null;
}

export interface SelectionOnGetProjects {
  status: string | null;
  data: Array<SelectionOnData | null> | null;
}

export interface GetProjects {
  getProjects: SelectionOnGetProjects | null;
}

export interface GraphQLWrapper {
  query: string
  name: string
  operation: OperationTypeNode
 }
export declare const GQL: GraphQLWrapper