/**
 * This file is autogenerated from gql:compile script using index.graphql .
 * Any changes made to this file will be overwritten in build.
 * It won't be committed into git.
 **/

import {OperationTypeNode} from 'graphql'
import {TriggerRules} from '../../../../gql-enums/trigger-rules.enum'
import {RepositoryType} from '../../../../gql-enums/repository-type.enum'
export interface GetWorkflowRunDetailsInput {
  workflowId?: string | null;
  runId?: string | null;
}

export interface SelectionOnEvents {
  timestamp: string | null;
  status: string | null;
  message: string | null;
}

export interface SelectionOnHaConfig {
  enable_ha: boolean | null;
}

export interface SelectionOnNotificationPreference {
  on_fail: boolean | null;
}

export interface SelectionOnAttachedCluster {
  cluster_id: string | null;
  runtime: string | null;
  cluster_name: string | null;
  cluster_status: string | null;
  memory: number | null;
  cores: number | null;
  ray_dashboard: string | null;
  logs_dashboard: string | null;
  events_dashboard: string | null;
  estimated_cost: string | null;
  created_at: string | null;
}

export interface SelectionOnMetadata {
  repository: RepositoryType | null;
  exclusions: string | null;
}

export interface SelectionOnBody {
  path: string | null;
  name: string | null;
  version: string | null;
  metadata: SelectionOnMetadata | null;
}

export interface SelectionOnPackages {
  source: string | null;
  body: SelectionOnBody | null;
}

export interface SelectionOnTasks {
  task_name: string | null;
  source_type: string | null;
  source: string | null;
  file_path: string | null;
  ha_config: SelectionOnHaConfig | null;
  notify_on: string | null;
  trigger_rule: TriggerRules | null;
  notification_preference: SelectionOnNotificationPreference | null;
  attached_cluster: SelectionOnAttachedCluster | null;
  dependent_libraries: string | null;
  packages: Array<SelectionOnPackages | null> | null;
  input_parameters: any | null;
  dynamic_artifact: boolean | null;
  retries: number | null;
  timeout: number | null;
  depends_on: Array<string | null> | null;
  task_validation_status: string | null;
  run_status: string | null;
}

export interface SelectionOnRepairRun {
  status: string | null;
}

export interface SelectionOnData {
  workflow_id: string | null;
  run_id: string | null;
  start_time: string | null;
  end_time: string | null;
  duration: number | null;
  run_status: string | null;
  trigger: string | null;
  trigger_by: string | null;
  is_run_duration_exceeded: boolean | null;
  expected_run_duration: number | null;
  parameters: any | null;
  events: Array<SelectionOnEvents | null> | null;
  tasks: Array<SelectionOnTasks | null> | null;
  repair_run: SelectionOnRepairRun | null;
}

export interface SelectionOnGetWorkflowRunDetails {
  data: SelectionOnData | null;
}

export interface GetWorkflowRunDetails {
  getWorkflowRunDetails: SelectionOnGetWorkflowRunDetails | null;
}


export interface GraphQLWrapper {
  query: string
  name: string
  operation: OperationTypeNode
 }
export declare const GQL: GraphQLWrapper