/**
 * This file is autogenerated from gql:compile script using index.graphql .
 * Any changes made to this file will be overwritten in build.
 * It won't be committed into git.
 **/

import {OperationTypeNode} from 'graphql'
import {RepositoryType} from '../../../../../gql-enums/repository-type.enum'
import {ApiStatus} from '../../../../../gql-enums/api-status.enum'
export interface GetMavenPackagesInput {
  search?: string | null;
  page_size?: number | null;
  offset?: number | null;
  repository?: RepositoryType | null;
}

export interface SelectionOnPackages {
  group_id: string | null;
  artifact_id: string | null;
  version: string | null;
}

export interface SelectionOnData {
  result_size: number | null;
  packages: Array<SelectionOnPackages | null> | null;
}

export interface SelectionOnGetMavenPackages {
  status: ApiStatus | null;
  message: string | null;
  data: SelectionOnData | null;
}

export interface GetMavenPackages {
  getMavenPackages: SelectionOnGetMavenPackages | null;
}


export interface GraphQLWrapper {
  query: string
  name: string
  operation: OperationTypeNode
 }
export declare const GQL: GraphQLWrapper