/**
 * This file is autogenerated from gql:compile script using startCluster.graphql .
 * Any changes made to this file will be overwritten in build.
 * It won't be committed into git.
 **/

import {OperationTypeNode} from 'graphql'

export interface StartClusterInput {
  input?: {
    cluster_id?: string | null;
  } | null;
}

export interface SelectionOnData {
  cluster_id: string | null;
}

export interface SelectionOnStartCluster {
  status: string | null;
  data: SelectionOnData | null;
}

export interface StartCluster {
  startCluster: SelectionOnStartCluster | null;
}

export interface GraphQLWrapper {
  query: string
  name: string
  operation: OperationTypeNode
 }
export declare const GQL: GraphQLWrapper