/**
 * This file is autogenerated from gql:compile script using index.graphql .
 * Any changes made to this file will be overwritten in build.
 * It won't be committed into git.
 **/

import {OperationTypeNode} from 'graphql'

export interface GetFeatureGroupEntitiesInput {
  featureGroupName?: string | null;
  version?: number | null;
}

export interface SelectionOnData {
  description: string | null;
  entityName: string | null;
  joinKeys: Array<string | null> | null;
  tags: Array<string | null> | null;
  type: Array<string | null> | null;
}

export interface SelectionOnGetFeatureGroupEntities {
  status: string | null;
  statusCode: number | null;
  data: Array<SelectionOnData | null> | null;
}

export interface GetFeatureGroupEntities {
  getFeatureGroupEntities: SelectionOnGetFeatureGroupEntities | null;
}

export interface GraphQLWrapper {
  query: string
  name: string
  operation: OperationTypeNode
 }
export declare const GQL: GraphQLWrapper