/**
 * This file is autogenerated from gql:compile script using getDataSourceEnvironments.graphql .
 * Any changes made to this file will be overwritten in build.
 * It won't be committed into git.
 **/

import {OperationTypeNode} from 'graphql'

export interface SelectionOnGetDataSourceEnvironments {
  data: Array<string | null> | null;
  message: string | null;
  status: string | null;
}

export interface GetDataSourceEnvironments {
  getDataSourceEnvironments: SelectionOnGetDataSourceEnvironments | null;
}

export interface GraphQLWrapper {
  query: string
  name: string
  operation: OperationTypeNode
 }
export declare const GQL: GraphQLWrapper