/**
 * This file is autogenerated from gql:compile script using index.graphql .
 * Any changes made to this file will be overwritten in build.
 * It won't be committed into git.
 **/

import {OperationTypeNode} from 'graphql'

export interface JobClusterDefinitionInput {
  jobClusterDefinitionId?: string | null;
}

export interface SelectionOnRuntime {
  id: string | null;
  displayName: string | null;
}

export interface SelectionOnParams {
  headNodeCpuUsageThreshold: number | null;
  workerNodeCpuUsageThreshold: number | null;
}

export interface SelectionOnAutoTerminationPolicies {
  policyName: string | null;
  enabled: boolean | null;
  params: SelectionOnParams | null;
}

export interface SelectionOnTemplate {
  id: string | null;
  displayName: string | null;
  memoryPerCore: string | null;
  templateId: string | null;
}

export interface SelectionOnGpuPod {
  name: string | null;
  cores: number | null;
  memory: number | null;
  gpuCount: number | null;
  gRamMemory: number | null;
  gRamType: string | null;
}

export interface SelectionOnHeadNodeConfig {
  cores: number | null;
  memory: number | null;
  nodeType: string | null;
  nodeCapacityType: string | null;
  gpuPod: SelectionOnGpuPod | null;
}

export interface SelectionOnDiskSetting {
  diskType: string | null;
  storageSize: number | null;
}

export interface SelectionOnWorkerNodeConfigs {
  coresPerPods: number | null;
  memoryPerPods: number | null;
  minPods: number | null;
  maxPods: number | null;
  diskSetting: SelectionOnDiskSetting | null;
  nodeType: string | null;
  nodeCapacityType: string | null;
  gpuPod: SelectionOnGpuPod | null;
}

export interface SelectionOnInstanceRole {
  id: number | null;
  displayName: string | null;
  roleId: string | null;
}

export interface SelectionOnAvailabilityZone {
  id: number | null;
  displayName: string | null;
  zoneId: string | null;
}

export interface SelectionOnRayParams {
  objectStoreMemory: number | null;
  cpusOnHead: number | null;
}

export interface SelectionOnAdvanceConfig {
  environmentVariables: string | null;
  spark_config: any | null;
  logPath: string | null;
  initScript: string | null;
  instanceRole: SelectionOnInstanceRole | null;
  availabilityZone: SelectionOnAvailabilityZone | null;
  rayParams: SelectionOnRayParams | null;
}

export interface SelectionOnDashboards {
  rayDashboardUrl: string | null;
  sparkUIUrl: string | null;
  grafanaDashboardUrl: string | null;
  resourceUtilizationDashboardUrl: string | null;
}

export interface SelectionOnData {
  clusterId: string | null;
  clusterName: string | null;
  isJobCluster: boolean | null;
  status: string | null;
  tags: Array<string | null> | null;
  runtime: SelectionOnRuntime | null;
  inactiveTime: number | null;
  autoTerminationPolicies: Array<SelectionOnAutoTerminationPolicies | null> | null;
  template: SelectionOnTemplate | null;
  user: string | null;
  headNodeConfig: SelectionOnHeadNodeConfig | null;
  workerNodeConfigs: Array<SelectionOnWorkerNodeConfigs | null> | null;
  advanceConfig: SelectionOnAdvanceConfig | null;
  dashboards: SelectionOnDashboards | null;
  createdOn: string | null;
  createdAt: string | null;
  estimatedCost: string | null;
}

export interface SelectionOnJobClusterDefinition {
  data: SelectionOnData | null;
}

export interface JobClusterDefinition {
  jobClusterDefinition: SelectionOnJobClusterDefinition | null;
}

export interface GraphQLWrapper {
  query: string
  name: string
  operation: OperationTypeNode
 }
export declare const GQL: GraphQLWrapper