/**
 * This file is autogenerated from gql:compile script using index.graphql .
 * Any changes made to this file will be overwritten in build.
 * It won't be committed into git.
 **/

import {OperationTypeNode} from 'graphql'

export interface GetWorkflowRunsInput {
  workflowId?: string | null;
  tags?: Array<string | null> | null;
  startDate?: string | null;
  endDate?: string | null;
  pageSize?: number | null;
  offset?: number | null;
  sortBy?: string | null;
  sortOrder?: string | null;
  filters?: Array<string | null> | null;
}

export interface SelectionOnRuns {
  duration: number | null;
  run_id: string | null;
  run_status: string | null;
  start_time: string | null;
  trigger: string | null;
  trigger_by: string | null;
  is_run_duration_exceeded: boolean | null;
  expected_run_duration: number | null;
}

export interface SelectionOnRepairRun {
  run_id: string | null;
  status: string | null;
}

export interface SelectionOnData {
  workflow_id: string | null;
  runs: Array<SelectionOnRuns | null> | null;
  repair_run: SelectionOnRepairRun | null;
}

export interface SelectionOnGetWorkflowRuns {
  offset: number | null;
  page_size: number | null;
  result_size: number | null;
  data: SelectionOnData | null;
}

export interface GetWorkflowRuns {
  getWorkflowRuns: SelectionOnGetWorkflowRuns | null;
}

export interface GraphQLWrapper {
  query: string
  name: string
  operation: OperationTypeNode
 }
export declare const GQL: GraphQLWrapper