/**
 * This file is autogenerated from gql:compile script using launchCodespace.graphql .
 * Any changes made to this file will be overwritten in build.
 * It won't be committed into git.
 **/

import {OperationTypeNode} from 'graphql'

export interface LaunchCodespaceInput {
  projectId?: string | null;
  codespaceId?: string | null;
}

export interface SelectionOnClusterUsage {
  memory_used: number | null;
  cores_used: number | null;
}

export interface SelectionOnAttachedCluster {
  cluster_id: string | null;
  cluster_name: string | null;
  cluster_status: string | null;
  memory: number | null;
  cores: number | null;
  cluster_usage: SelectionOnClusterUsage | null;
  attached_codespaces_count: number | null;
  ray_dashboard: string | null;
  prometheus_dashboard: string | null;
  spark_ui_dashboard: string | null;
}

export interface SelectionOnLaunchCodespace {
  project_id: string | null;
  project_name: string | null;
  codespace_id: string | null;
  codespace_name: string | null;
  github_link: string | null;
  last_sync_time: string | null;
  jupyter_lab_link: string | null;
  attached_cluster: SelectionOnAttachedCluster | null;
  code_server_link: string | null;
}

export interface LaunchCodespace {
  launchCodespace: SelectionOnLaunchCodespace | null;
}

export interface GraphQLWrapper {
  query: string
  name: string
  operation: OperationTypeNode
 }
export declare const GQL: GraphQLWrapper