/**
 * This file is autogenerated from gql:compile script using index.graphql .
 * Any changes made to this file will be overwritten in build.
 * It won't be committed into git.
 **/

import {OperationTypeNode} from 'graphql'
import {RuntimeStatus} from '../../../../../gql-enums/runtime-status.enum'
export interface GetRuntimeDetailsInput {
  runtimeName: string;
}

export interface SelectionOnGetRuntimeDetails {
  status: RuntimeStatus;
  logs: string;
}

export interface GetRuntimeDetails {
  getRuntimeDetails: SelectionOnGetRuntimeDetails | null;
}


export interface GraphQLWrapper {
  query: string
  name: string
  operation: OperationTypeNode
 }
export declare const GQL: GraphQLWrapper