/**
 * This file is autogenerated from gql:compile script using getDataSourceSourcesForEnvironment.graphql .
 * Any changes made to this file will be overwritten in build.
 * It won't be committed into git.
 **/

import {OperationTypeNode} from 'graphql'

export interface GetDataSourceSourcesForEnvironmentInput {
  env?: string | null;
}

export interface SelectionOnGetDataSourceSourcesForEnvironment {
  data: Array<string | null> | null;
  message: string | null;
  status: string | null;
}

export interface GetDataSourceSourcesForEnvironment {
  getDataSourceSourcesForEnvironment: SelectionOnGetDataSourceSourcesForEnvironment | null;
}

export interface GraphQLWrapper {
  query: string
  name: string
  operation: OperationTypeNode
 }
export declare const GQL: GraphQLWrapper