/**
 * This file is autogenerated from gql:compile script using index.graphql .
 * Any changes made to this file will be overwritten in build.
 * It won't be committed into git.
 **/

import {OperationTypeNode} from 'graphql'
import {ApiStatus} from '../../../../../gql-enums/api-status.enum'
export interface GetComputeRuntimeDetailsInput {
  runtime?: string | null;
}

export interface SelectionOnComponents {
  name: string | null;
  version: string | null;
}

export interface SelectionOnData {
  id: number | null;
  class: string | null;
  type: string | null;
  runtime: string | null;
  image: string | null;
  reference_link: string | null;
  components: Array<SelectionOnComponents | null> | null;
  created_by: string | null;
  last_updated_by: string | null;
  created_at: string | null;
  last_updated_at: string | null;
  is_deleted: boolean | null;
  spark_connect: boolean | null;
  spark_auto_init: boolean | null;
}

export interface SelectionOnGetComputeRuntimeDetails {
  status: ApiStatus | null;
  message: string | null;
  data: SelectionOnData | null;
}

export interface GetComputeRuntimeDetails {
  getComputeRuntimeDetails: SelectionOnGetComputeRuntimeDetails | null;
}


export interface GraphQLWrapper {
  query: string
  name: string
  operation: OperationTypeNode
 }
export declare const GQL: GraphQLWrapper