/**
 * This file is autogenerated from gql:compile script using index.graphql .
 * Any changes made to this file will be overwritten in build.
 * It won't be committed into git.
 **/

import {OperationTypeNode} from 'graphql'
import {ModelDeploymentModelStatus} from '../../../../../gql-enums/model-deployment-model-status.enum'
import {ModelDeploymentSortBy} from '../../../../../gql-enums/model-deployment-sort-by.enum'
import {ModelDeploymentSortOrder} from '../../../../../gql-enums/model-deployment-sort-order.enum'
import {ModelDeploymentModelType} from '../../../../../gql-enums/model-deployment-model-type.enum'
import {CompatibleAppVersionStatus} from '../../../../../gql-enums/compatible-app-version-status.enum'
export interface GetModelDeploymentsInput {
  filters?: {
    name?: string | null;
    status?: ModelDeploymentModelStatus | null;
    owners?: Array<string> | null;
  } | null;
  pageSize?: number | null;
  pageNumber?: number | null;
  sortBy?: ModelDeploymentSortBy | null;
  sortOrder?: ModelDeploymentSortOrder | null;
}

export interface SelectionOnCompatibleAppVersions {
  id: string | null;
  semver: string | null;
  codepushVersion: string | null;
  buildNumber: number | null;
  status: CompatibleAppVersionStatus | null;
  appName: string | null;
  createdAt: string | null;
  lastUpdatedAt: string | null;
}

export interface SelectionOnMlModelDeployments {
  id: string | null;
  deploymentName: string | null;
  modelType: ModelDeploymentModelType | null;
  description: string | null;
  modelName: string | null;
  mlFlowModel: string | null;
  mlFlowVersion: number | null;
  tags: Array<string>;
  status: string | null;
  owner: string | null;
  lastUpdatedAt: string | null;
  createdAt: string | null;
  compatibleAppVersions: Array<SelectionOnCompatibleAppVersions>;
}

export interface SelectionOnData {
  totalDeployments: number | null;
  pageNumber: number | null;
  hasNextPage: boolean | null;
  mlModelDeployments: Array<SelectionOnMlModelDeployments>;
}

export interface SelectionOnGetModelDeployments {
  data: SelectionOnData;
}

export interface GetModelDeployments {
  getModelDeployments: SelectionOnGetModelDeployments | null;
}


export interface GraphQLWrapper {
  query: string
  name: string
  operation: OperationTypeNode
 }
export declare const GQL: GraphQLWrapper