/**
 * This file is autogenerated from gql:compile script using index.graphql .
 * Any changes made to this file will be overwritten in build.
 * It won't be committed into git.
 **/

import {OperationTypeNode} from 'graphql'
import {ApiStatus} from '../../../../../gql-enums/api-status.enum'
export interface GetMavenPackageVersionsInput {
  group_id?: string | null;
  artifact_id?: string | null;
}

export interface SelectionOnData {
  artifact_id: string | null;
  group_id: string | null;
  versions: Array<string | null> | null;
}

export interface SelectionOnGetMavenPackageVersions {
  status: ApiStatus | null;
  message: string | null;
  data: SelectionOnData | null;
}

export interface GetMavenPackageVersions {
  getMavenPackageVersions: SelectionOnGetMavenPackageVersions | null;
}


export interface GraphQLWrapper {
  query: string
  name: string
  operation: OperationTypeNode
 }
export declare const GQL: GraphQLWrapper