/**
 * This file is autogenerated from gql:compile script using index.graphql .
 * Any changes made to this file will be overwritten in build.
 * It won't be committed into git.
 **/

import {OperationTypeNode} from 'graphql'

export interface SearchAssetsInput {
  asset_name_regex?: string | null;
  asset_prefix_regex?: string | null;
  page_size?: number | null;
  offset?: number | null;
  depth?: number | null;
}

export interface SelectionOnData {
  asset_name: string | null;
  asset_prefix: string | null;
  depth: number | null;
  is_terminal: boolean | null;
}

export interface SelectionOnSearchAssets {
  total: number | null;
  offset: number | null;
  page_size: number | null;
  data: Array<SelectionOnData | null> | null;
}

export interface SearchAssets {
  searchAssets: SelectionOnSearchAssets | null;
}

export interface GraphQLWrapper {
  query: string
  name: string
  operation: OperationTypeNode
 }
export declare const GQL: GraphQLWrapper