/**
 * This file is autogenerated from gql:compile script using index.graphql .
 * Any changes made to this file will be overwritten in build.
 * It won't be committed into git.
 **/

import {OperationTypeNode} from 'graphql'

export interface SelectionOnAppVersions {
  appName: string;
  buildNumber: number | null;
  codepushVersion: string | null;
  id: string;
  semver: string;
}

export interface SelectionOnVersions {
  appName: string | null;
  appVersions: Array<SelectionOnAppVersions>;
}

export interface SelectionOnData {
  versions: Array<SelectionOnVersions>;
}

export interface SelectionOnGetAppVersions {
  data: SelectionOnData | null;
}

export interface GetAppVersions {
  getAppVersions: SelectionOnGetAppVersions | null;
}

export interface GraphQLWrapper {
  query: string
  name: string
  operation: OperationTypeNode
 }
export declare const GQL: GraphQLWrapper