/**
 * This file is autogenerated from gql:compile script using index.graphql .
 * Any changes made to this file will be overwritten in build.
 * It won't be committed into git.
 **/

import {OperationTypeNode} from 'graphql'
import {ApiStatus} from '../../../../../gql-enums/api-status.enum'
import {LibraryStatus} from '../../../../../gql-enums/library-status.enum'
export interface InstallLibraryInput {
  clusterId?: string | null;
  packages?: Array<{
    source?: string | null;
    body?: any | null;
  } | null> | null;
}

export interface SelectionOnPackages {
  id: string | null;
  name: string | null;
  version: string | null;
  status: LibraryStatus | null;
}

export interface SelectionOnData {
  cluster_id: string | null;
  packages: Array<SelectionOnPackages | null> | null;
}

export interface SelectionOnInstallLibrary {
  status: ApiStatus | null;
  message: string | null;
  data: SelectionOnData | null;
}

export interface InstallLibrary {
  installLibrary: SelectionOnInstallLibrary | null;
}


export interface GraphQLWrapper {
  query: string
  name: string
  operation: OperationTypeNode
 }
export declare const GQL: GraphQLWrapper