/**
 * This file is autogenerated from gql:compile script using editProject.graphql .
 * Any changes made to this file will be overwritten in build.
 * It won't be committed into git.
 **/

import {OperationTypeNode} from 'graphql'

export interface EditProjectInput {
  projectId?: string | null;
  projectName?: string | null;
}

export interface SelectionOnEditProject {
  status: string | null;
}

export interface EditProject {
  editProject: SelectionOnEditProject | null;
}

export interface GraphQLWrapper {
  query: string
  name: string
  operation: OperationTypeNode
 }
export declare const GQL: GraphQLWrapper