/**
 * This file is autogenerated from gql:compile script using index.graphql .
 * Any changes made to this file will be overwritten in build.
 * It won't be committed into git.
 **/

import {OperationTypeNode} from 'graphql'
import {ApiStatus} from '../../../../gql-enums/api-status.enum'
export interface GetFeatureGroupFiltersInput {
  user?: string | null;
}

export interface SelectionOnData {
  name: string | null;
  value: Array<string | null> | null;
}

export interface SelectionOnGetFeatureGroupFilters {
  status: ApiStatus | null;
  statusCode: number | null;
  data: Array<SelectionOnData | null> | null;
}

export interface GetFeatureGroupFilters {
  getFeatureGroupFilters: SelectionOnGetFeatureGroupFilters | null;
}


export interface GraphQLWrapper {
  query: string
  name: string
  operation: OperationTypeNode
 }
export declare const GQL: GraphQLWrapper