/**
 * This file is autogenerated from gql:compile script using index.graphql .
 * Any changes made to this file will be overwritten in build.
 * It won't be committed into git.
 **/

import {OperationTypeNode} from 'graphql'

export interface GetWorkflowsAttachedToClusterInput {
  clusterId: string;
}

export interface SelectionOnGetWorkflowsAttachedToCluster {
  workflow_name: string | null;
  display_name: string | null;
  description: string | null;
  status: string | null;
  workflow_id: string | null;
  tags: Array<string | null> | null;
  schedule: string | null;
  next_run_time: string | null;
  owner: string | null;
}

export interface GetWorkflowsAttachedToCluster {
  getWorkflowsAttachedToCluster: Array<SelectionOnGetWorkflowsAttachedToCluster | null> | null;
}

export interface GraphQLWrapper {
  query: string
  name: string
  operation: OperationTypeNode
 }
export declare const GQL: GraphQLWrapper