/**
 * This file is autogenerated from gql:compile script using index.graphql .
 * Any changes made to this file will be overwritten in build.
 * It won't be committed into git.
 **/

import {OperationTypeNode} from 'graphql'

export interface UpdateWorkflowTagsInput {
  workflowId?: string | null;
  tags?: Array<string | null> | null;
}

export interface SelectionOnData {
  workflow_id: string | null;
  tags: Array<string | null> | null;
}

export interface SelectionOnUpdateWorkflowTags {
  data: SelectionOnData | null;
}

export interface UpdateWorkflowTags {
  updateWorkflowTags: SelectionOnUpdateWorkflowTags | null;
}

export interface GraphQLWrapper {
  query: string
  name: string
  operation: OperationTypeNode
 }
export declare const GQL: GraphQLWrapper