/**
 * This file is autogenerated from gql:compile script using index.graphql .
 * Any changes made to this file will be overwritten in build.
 * It won't be committed into git.
 **/

import {OperationTypeNode} from 'graphql'

export interface GetWorkflowsInput {
  query?: string | null;
  filters?: {
    user?: Array<string | null> | null;
    status?: Array<string | null> | null;
  } | null;
  pageSize?: number | null;
  offset?: number | null;
  sortBy?: string | null;
  sortOrder?: string | null;
}

export interface SelectionOnLastRunDetails {
  run_status: string | null;
  is_run_duration_exceeded: boolean | null;
  expected_run_duration: number | null;
}

export interface SelectionOnData {
  workflow_name: string | null;
  display_name: string | null;
  description: string | null;
  status: string | null;
  workflow_id: string | null;
  tags: Array<string | null> | null;
  schedule: string | null;
  last_run_details: Array<SelectionOnLastRunDetails | null> | null;
  next_run_time: string | null;
  owner: string | null;
}

export interface SelectionOnGetWorkflows {
  result_size: number | null;
  page_size: number | null;
  offset: number | null;
  data: Array<SelectionOnData | null> | null;
}

export interface GetWorkflows {
  getWorkflows: SelectionOnGetWorkflows | null;
}

export interface GraphQLWrapper {
  query: string
  name: string
  operation: OperationTypeNode
 }
export declare const GQL: GraphQLWrapper