/**
 * This file is autogenerated from gql:compile script using checkUniqueLink.graphql .
 * Any changes made to this file will be overwritten in build.
 * It won't be committed into git.
 **/

import {OperationTypeNode} from 'graphql'

export interface CheckUniqueLinkInput {
  githubLink?: string | null;
}

export interface SelectionOnData {
  is_unique: boolean | null;
}

export interface SelectionOnCheckUniqueLink {
  status: string | null;
  data: SelectionOnData | null;
}

export interface CheckUniqueLink {
  checkUniqueLink: SelectionOnCheckUniqueLink | null;
}

export interface GraphQLWrapper {
  query: string
  name: string
  operation: OperationTypeNode
 }
export declare const GQL: GraphQLWrapper