/**
 * This file is autogenerated from gql:compile script using index.graphql .
 * Any changes made to this file will be overwritten in build.
 * It won't be committed into git.
 **/

import {OperationTypeNode} from 'graphql'
import {ApiStatus} from '../../../../gql-enums/api-status.enum'
import {RunStatus} from '../../../../gql-enums/run-status.enum'
export interface GetFeatureGroupsInput {
  searchString?: string | null;
  pageSize?: number | null;
  offset?: number | null;
  sortBy?: string | null;
  sortOrder?: string | null;
  filters?: Array<{
    name?: string | null;
    value?: Array<string | null> | null;
  } | null> | null;
  type?: string | null;
  user?: string | null;
}

export interface SelectionOnCopyCode {
  name: string | null;
  value: string | null;
}

export interface SelectionOnData {
  id: string | null;
  title: string | null;
  description: string | null;
  version: number | null;
  allVersions: Array<number | null> | null;
  featuresCount: number | null;
  devUsage: number | null;
  prodUsage: number | null;
  lastValueUpdated: string | null;
  createdBy: string | null;
  tags: Array<string | null> | null;
  lastFiveRuns: Array<RunStatus | null> | null;
  type: string | null;
  typesAvailable: Array<string | null> | null;
  copyCode: Array<SelectionOnCopyCode | null> | null;
}

export interface SelectionOnGetFeatureGroups {
  status: ApiStatus | null;
  statusCode: number | null;
  resultSize: number | null;
  pageSize: number | null;
  offset: number | null;
  totalRecordsCount: number | null;
  data: Array<SelectionOnData | null> | null;
}

export interface GetFeatureGroups {
  getFeatureGroups: SelectionOnGetFeatureGroups | null;
}


export interface GraphQLWrapper {
  query: string
  name: string
  operation: OperationTypeNode
 }
export declare const GQL: GraphQLWrapper