/**
 * This file is autogenerated from gql:compile script using index.graphql .
 * Any changes made to this file will be overwritten in build.
 * It won't be committed into git.
 **/

import {OperationTypeNode} from 'graphql'

export interface AddRecentlyVisitedClusterInput {
  clusterId?: string | null;
}

export interface SelectionOnAddRecentlyVisitedCluster {
  status: string | null;
}

export interface AddRecentlyVisitedCluster {
  addRecentlyVisitedCluster: SelectionOnAddRecentlyVisitedCluster | null;
}

export interface GraphQLWrapper {
  query: string
  name: string
  operation: OperationTypeNode
 }
export declare const GQL: GraphQLWrapper