/**
 * This file is autogenerated from gql:compile script using index.graphql .
 * Any changes made to this file will be overwritten in build.
 * It won't be committed into git.
 **/

import {OperationTypeNode} from 'graphql'
import {ApiStatus} from '../../../../gql-enums/api-status.enum'
export interface GetFeaturesInput {
  searchString?: string | null;
  featureGroupId?: string | null;
  version?: number | null;
  pageSize?: number | null;
  offset?: number | null;
  sortBy?: string | null;
  sortOrder?: string | null;
  type?: string | null;
}

export interface SelectionOnCopyCode {
  name: string | null;
  value: string | null;
}

export interface SelectionOnUsage {
  prodCount: number | null;
  devCount: number | null;
}

export interface SelectionOnData {
  title: string | null;
  description: string | null;
  tags: Array<string | null> | null;
  type: string | null;
  copyCode: Array<SelectionOnCopyCode | null> | null;
  isPrimaryKey: boolean | null;
  usage: SelectionOnUsage | null;
}

export interface SelectionOnGetFeatures {
  status: ApiStatus | null;
  statusCode: number | null;
  resultSize: number | null;
  pageSize: number | null;
  offset: number | null;
  totalRecordsCount: number | null;
  data: Array<SelectionOnData | null> | null;
}

export interface GetFeatures {
  getFeatures: SelectionOnGetFeatures | null;
}


export interface GraphQLWrapper {
  query: string
  name: string
  operation: OperationTypeNode
 }
export declare const GQL: GraphQLWrapper