#!/usr/bin/env node
"use strict";
var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
    function adopt(value) { return value instanceof P ? value : new P(function (resolve) { resolve(value); }); }
    return new (P || (P = Promise))(function (resolve, reject) {
        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
        function rejected(value) { try { step(generator["throw"](value)); } catch (e) { reject(e); } }
        function step(result) { result.done ? resolve(result.value) : adopt(result.value).then(fulfilled, rejected); }
        step((generator = generator.apply(thisArg, _arguments || [])).next());
    });
};
var __generator = (this && this.__generator) || function (thisArg, body) {
    var _ = { label: 0, sent: function() { if (t[0] & 1) throw t[1]; return t[1]; }, trys: [], ops: [] }, f, y, t, g;
    return g = { next: verb(0), "throw": verb(1), "return": verb(2) }, typeof Symbol === "function" && (g[Symbol.iterator] = function() { return this; }), g;
    function verb(n) { return function (v) { return step([n, v]); }; }
    function step(op) {
        if (f) throw new TypeError("Generator is already executing.");
        while (_) try {
            if (f = 1, y && (t = op[0] & 2 ? y["return"] : op[0] ? y["throw"] || ((t = y["return"]) && t.call(y), 0) : y.next) && !(t = t.call(y, op[1])).done) return t;
            if (y = 0, t) op = [op[0] & 2, t.value];
            switch (op[0]) {
                case 0: case 1: t = op; break;
                case 4: _.label++; return { value: op[1], done: false };
                case 5: _.label++; y = op[1]; op = [0]; continue;
                case 7: op = _.ops.pop(); _.trys.pop(); continue;
                default:
                    if (!(t = _.trys, t = t.length > 0 && t[t.length - 1]) && (op[0] === 6 || op[0] === 2)) { _ = 0; continue; }
                    if (op[0] === 3 && (!t || (op[1] > t[0] && op[1] < t[3]))) { _.label = op[1]; break; }
                    if (op[0] === 6 && _.label < t[1]) { _.label = t[1]; t = op; break; }
                    if (t && _.label < t[2]) { _.label = t[2]; _.ops.push(op); break; }
                    if (t[2]) _.ops.pop();
                    _.trys.pop(); continue;
            }
            op = body.call(thisArg, _);
        } catch (e) { op = [6, e]; y = 0; } finally { f = t = 0; }
        if (op[0] & 5) throw op[1]; return { value: op[0] ? op[1] : void 0, done: true };
    }
};
var __spreadArray = (this && this.__spreadArray) || function (to, from, pack) {
    if (pack || arguments.length === 2) for (var i = 0, l = from.length, ar; i < l; i++) {
        if (ar || !(i in from)) {
            if (!ar) ar = Array.prototype.slice.call(from, 0, i);
            ar[i] = from[i];
        }
    }
    return to.concat(ar || Array.prototype.slice.call(from));
};
Object.defineProperty(exports, "__esModule", { value: true });
var from_query_1 = require("@gql2ts/from-query");
var language_typescript_1 = require("@gql2ts/language-typescript");
var prettier_1 = require("prettier");
var ts_2_iots_1 = require("./ts-2-iots");
var fs = require("fs-extra");
var Glob = require("glob");
var graphql = require("graphql");
var path = require("path");
var util_1 = require("util");
var NO_OF_DIRECTORIES_OFFSET = 2;
var Kind = graphql.Kind;
var glob = (0, util_1.promisify)(Glob);
var formatConfig = {
    singleQuote: true,
    jsxSingleQuote: true,
    semi: false,
    bracketSpacing: false
};
var readFile = (0, util_1.promisify)(fs.readFile);
var writeFile = ((0, util_1.promisify)(fs.writeFile));
var removeWhiteSpace = function (q) {
    return q.replace(/\n/g, '').replace(/\s\s*/g, ' ');
};
var identity = function (arg) { return arg; };
var getAutogenerationComment = function (fileName) {
    return "/**\n * This file is autogenerated from gql:compile script using ".concat(fileName, " .\n * Any changes made to this file will be overwritten in build.\n * It won't be committed into git.\n **/\n");
};
var titleCaseToHyphen = function (str) {
    return str
        .replace(/[A-Z]/, function (g) {
        return g.toLowerCase();
    })
        .replace(/[A-Z]/g, function (g) {
        return '-' + g.toLowerCase();
    });
};
var writeEnumsFile = function (enumName, enumData, rootPath) {
    try {
        var enumFileName = titleCaseToHyphen(enumName);
        return writeFile("".concat(rootPath, "/gql-enums/").concat(enumFileName, ".enum.ts"), "".concat(getAutogenerationComment('graphql.schema.json'), "\n").concat(enumData));
    }
    catch (e) {
        console.log("FAILED  to write enums file : ".concat(enumName, "\n\n"), e); //tslint:disable-line
        process.exit(1);
    }
};
var getEnumImportText = function (enumNames, noOfDirectoriesToGoUp) {
    return enumNames
        .map(function (enumName) {
        return "import {".concat(enumName, "} from '").concat('../'.repeat(noOfDirectoriesToGoUp), "gql-enums/").concat(titleCaseToHyphen(enumName), ".enum'");
    })
        .join('\n');
};
var parseQuery = function (data, queryString, filePath, processingDirectory) {
    var enumsData = {};
    var saveEnumData = function (enumName, enumText) {
        enumsData[enumName] = language_typescript_1.default.postProcessor('export ' + language_typescript_1.default.enumTypeBuilder(enumName, enumText));
        return '';
    };
    var customFormattersWithoutEnums = {
        interfaceBuilder: function (name, body) {
            return 'export ' + language_typescript_1.default.interfaceBuilder(name, body);
        },
        enumTypeBuilder: saveEnumData,
        typeBuilder: function (name, body) {
            return 'export ' + language_typescript_1.default.typeBuilder(name, body);
        },
        exportFunction: identity
    };
    var parsedQuery = (0, from_query_1.default)(data, queryString, {}, customFormattersWithoutEnums).map(function (i) { return i.result; });
    var enumNames = Object.keys(enumsData);
    var fileName = filePath.replace(/.*\/(.*).graphql/, '$1');
    var noOfDirectoriesToGoUp = filePath.replace(new RegExp('.*' + processingDirectory), '').split(path.sep)
        .length - NO_OF_DIRECTORIES_OFFSET;
    var definitionsFileText = __spreadArray(__spreadArray([
        getAutogenerationComment(fileName + '.graphql'),
        "import {OperationTypeNode} from 'graphql'",
        // Add import only when there are enums in the file
        enumNames.length ? getEnumImportText(enumNames, noOfDirectoriesToGoUp) : ''
    ], parsedQuery, true), [
        "export interface GraphQLWrapper {\n  query: string\n  name: string\n  operation: OperationTypeNode\n }",
        "export declare const GQL: GraphQLWrapper"
    ], false).join('\n');
    return { enumsData: enumsData, definitionsFileText: definitionsFileText };
};
var getQueryJSText = function (queryString) {
    var AST = graphql.parse(queryString);
    /**
     * Filter out any Fragments if they're defined
     * */
    var arrNodeDefinition = AST.definitions.filter(function (node) { return node.kind === Kind.OPERATION_DEFINITION; });
    /**
     * Typings get generated for last-defined node in the file
     * */
    var OperationNode = arrNodeDefinition[arrNodeDefinition.length - 1];
    var operation = OperationNode.operation, _a = OperationNode.name, _b = _a === void 0 ? { value: 'UnknownQueryOrMutation' } : _a, queryName = _b.value;
    var queryJS = "exports.GQL = {query:'".concat(removeWhiteSpace(queryString), "',name:'").concat(queryName, "',operation:'").concat(operation, "'}");
    return queryJS;
};
var compileFile = function (filePath, data, processingDirectory) { return __awaiter(void 0, void 0, void 0, function () {
    var queryString, queryJSText, parsedOutput, res, filesToWrite, e_1;
    return __generator(this, function (_a) {
        switch (_a.label) {
            case 0:
                _a.trys.push([0, 3, , 4]);
                return [4 /*yield*/, readFile(filePath)];
            case 1:
                queryString = (_a.sent()).toString();
                queryJSText = getQueryJSText(queryString);
                parsedOutput = parseQuery(data, queryString, filePath, processingDirectory);
                res = (0, ts_2_iots_1.getValidatorsFromString)(parsedOutput.definitionsFileText);
                filesToWrite = [
                    writeFile("".concat(filePath.replace('.graphql', '.d.ts')), parsedOutput.definitionsFileText),
                    writeFile("".concat(filePath.replace('.graphql', '.gqlTypes.ts')), (0, prettier_1.format)(res, formatConfig)),
                    writeFile("".concat(filePath.replace('.graphql', 'Gql.js')), (0, prettier_1.format)(queryJSText, formatConfig))
                ];
                return [4 /*yield*/, Promise.all(filesToWrite)];
            case 2:
                _a.sent();
                return [2 /*return*/, parsedOutput.enumsData];
            case 3:
                e_1 = _a.sent();
                console.log("FAILED: ".concat(filePath, "\n\n"), e_1); //tslint:disable-line
                process.exit(1);
                return [3 /*break*/, 4];
            case 4: return [2 /*return*/];
        }
    });
}); };
var main = function () { return __awaiter(void 0, void 0, void 0, function () {
    var data, args, _loop_1, i;
    return __generator(this, function (_a) {
        switch (_a.label) {
            case 0: return [4 /*yield*/, fs.readJSON('graphql.schema.json')];
            case 1:
                data = (_a.sent()).data;
                args = process.argv.slice(2);
                _loop_1 = function (i) {
                    var cwd, files, allEnumsArray, enumsData, allEnums;
                    return __generator(this, function (_b) {
                        switch (_b.label) {
                            case 0:
                                cwd = path.resolve(process.cwd(), args[i]);
                                return [4 /*yield*/, glob('**/*.graphql', {
                                        cwd: cwd
                                    })];
                            case 1:
                                files = _b.sent();
                                return [4 /*yield*/, Promise.all(files
                                        .map(function (i) { return path.resolve(cwd, i); })
                                        .map(function (path) { return compileFile(path, data, args[i]); }))];
                            case 2:
                                allEnumsArray = _b.sent();
                                enumsData = {};
                                allEnumsArray.forEach(function (enumsMap) {
                                    if (enumsMap) {
                                        Object.keys(enumsMap).forEach(function (enumName) {
                                            enumsData[enumName] = enumsMap[enumName];
                                        });
                                    }
                                });
                                allEnums = Object.keys(enumsData);
                                return [4 /*yield*/, Promise.all(allEnums.map(function (enumName) {
                                        return writeEnumsFile(enumName, enumsData[enumName], args[i]);
                                    }))];
                            case 3:
                                _b.sent();
                                console.log("Compiled ".concat(files.length, " files inside ").concat(args[i])); // tslint:disable-line
                                return [2 /*return*/];
                        }
                    });
                };
                i = 0;
                _a.label = 2;
            case 2:
                if (!(i < args.length)) return [3 /*break*/, 5];
                return [5 /*yield**/, _loop_1(i)];
            case 3:
                _a.sent();
                _a.label = 4;
            case 4:
                i++;
                return [3 /*break*/, 2];
            case 5: return [2 /*return*/];
        }
    });
}); };
main().catch(function (err) {
    console.error(err); // tslint:disable-line
    process.exit(1);
});
