/**
 * This file is autogenerated from gql:compile script using index.graphql .
 * Any changes made to this file will be overwritten in build.
 * It won't be committed into git.
 **/

import {OperationTypeNode} from 'graphql'

export interface GetSparkHistoryServerInput {
  resourceId: string;
}

export interface SelectionOnData {
  server_id: string | null;
  resource: string | null;
  user: string | null;
  ttl: number | null;
  started_at: string | null;
  status: string | null;
  id: string | null;
  url: string | null;
}

export interface SelectionOnGetSparkHistoryServer {
  status: string | null;
  data: SelectionOnData | null;
  message: string | null;
}

export interface GetSparkHistoryServer {
  getSparkHistoryServer: SelectionOnGetSparkHistoryServer | null;
}

export interface GraphQLWrapper {
  query: string
  name: string
  operation: OperationTypeNode
 }
export declare const GQL: GraphQLWrapper