/**
 * This file is autogenerated from gql:compile script using deleteCluster.graphql .
 * Any changes made to this file will be overwritten in build.
 * It won't be committed into git.
 **/

import {OperationTypeNode} from 'graphql'

export interface DeleteClusterInput {
  input?: {
    cluster_id?: string | null;
  } | null;
}

export interface SelectionOnData {
  cluster_id: string | null;
}

export interface SelectionOnDeleteCluster {
  status: string | null;
  data: SelectionOnData | null;
}

export interface DeleteCluster {
  deleteCluster: SelectionOnDeleteCluster | null;
}

export interface GraphQLWrapper {
  query: string
  name: string
  operation: OperationTypeNode
 }
export declare const GQL: GraphQLWrapper